// Question banks for Periodic Table Quest.
//
// Each topic has:
//   title       shown on the projector and phones
//   generators  built-in question types that are generated for every element
//               from the element data (see quiz.js). Use [] for a topic that
//               only uses your own questions.
//   questions   your own questions. Each one is:
//     el  element symbol ('Cl'), a list of symbols (['Cl','Br']), or null for a
//         general question that can appear on any element
//     q   the question (HTML allowed, e.g. <sub>2</sub>)
//     a   the correct answer
//     w   three wrong answers
//     x   a short explanation, shown after the student answers
//
// Steal challenges (harder, typed numeric answer) can be added the same way:
//     { el: 'Ne', steal: true, q: 'Question…', n: 20.18, tol: 0.01, dp: 2, x: 'Working…' }
//   n is the answer, tol how far off an answer may be and still count, dp the
//   decimal places to ask for. stealGenerators lists the built-in challenge types.
//
// To add a topic for another lecture, copy the "template" block at the bottom,
// rename it, fill in questions, and set topic: '<name>' in config.js.

window.PQ_BANKS = {

  atoms2: {
    title: 'Atoms 2: Electromagnetic radiation and energy levels',
    short: 'Atoms 2',
    generators: ['a2Freq', 'a2Lambda', 'a2Energy', 'a2Radio', 'a2Missing', 'a2Region', 'a2Highest', 'a2Photo', 'a2Gap', 'a2IonCompare', 'a2IonLambda'],
    generalWeight: 5,
    stealGenerators: ['s2IonLambda', 's2Line', 's2Kinetic', 's2Radio', 'stealPhoton'],
    questions: [
      // Waves and the spectrum
      { el: null, q: 'Wavelength and frequency are inversely proportional for electromagnetic radiation. Why?',
        a: 'All electromagnetic radiation travels at the same speed, c', w: ['Longer waves carry more energy', 'Photons slow down as frequency rises', 'Frequency and wavelength are measured in the same units'],
        x: 'c = λν with c fixed, so if more waves pass each second (higher ν), each wave must be shorter (smaller λ).' },
      { el: null, q: 'Which list is in order of increasing energy per photon?',
        a: 'Radio, infrared, visible, ultraviolet', w: ['Ultraviolet, visible, infrared, radio', 'Visible, radio, ultraviolet, infrared', 'Infrared, radio, visible, ultraviolet'],
        x: 'Energy per photon rises with frequency (E = hν), so it rises as wavelength falls: radio < microwave < infrared < visible < UV < X-rays.' },
      { el: null, q: 'NMR spectroscopy uses radio waves. What transitions does it involve?',
        a: 'Between nuclear spin levels in a magnetic field', w: ['Between electronic energy levels', 'Between molecular vibrational states', 'Ejection of core electrons'],
        x: 'Radio photons have very little energy, enough only for the tiny gaps between nuclear spin levels.' },
      { el: null, q: 'UV-visible spectroscopy probes transitions between…',
        a: 'electronic energy levels', w: ['nuclear spin levels', 'vibrational states', 'rotational states'],
        x: 'UV and visible photons have enough energy to move electrons between energy levels, which is also why atoms give coloured flames.' },

      // Photons and the photoelectric effect
      { el: 'K', q: 'Very bright visible light shines on potassium metal, but no electrons are ejected. Why not?',
        a: 'Each photon has too little energy, however many there are', w: ['The light is not bright enough yet', 'Potassium has no loosely held electrons', 'Visible light cannot reach a metal surface'],
        x: 'Brighter light means more photons per second, not more energy per photon. Ionisation needs each photon to carry enough energy on its own.' },
      { el: 'K', q: 'Shining UV light on potassium ejects electrons, but only above a threshold frequency of about…',
        a: '5 × 10<sup>14</sup> s<sup>−1</sup>', w: ['5 × 10<sup>8</sup> s<sup>−1</sup>', '5 × 10<sup>20</sup> s<sup>−1</sup>', '5 × 10<sup>−14</sup> s<sup>−1</sup>'],
        x: 'Below about 5 × 10<sup>14</sup> s<sup>−1</sup> (wavelength around 600 nm) each photon carries less than the 3.5 × 10<sup>−19</sup> J needed per atom.' },
      { el: null, q: 'Doubling the intensity of a beam of light, without changing its colour, doubles…',
        a: 'the number of photons per second', w: ['the energy of each photon', 'the frequency of the light', 'the wavelength of the light'],
        x: 'Intensity is the rate of photons. The energy of each photon depends only on its frequency, E = hν.' },
      { el: null, q: 'When a photon has more energy than is needed to eject an electron, the excess energy…',
        a: 'becomes the kinetic energy of the ejected electron', w: ['is re-emitted as a second photon', 'is lost: only the threshold energy is used', 'ejects a second electron'],
        x: 'In the lecture, 250 nm light on potassium has about 4.5 × 10<sup>−19</sup> J left over, which the electron carries away as kinetic energy.' },
      { el: null, q: 'Which experiment shows light behaving as a stream of particles?',
        a: 'The photoelectric effect', w: ['The double-slit experiment', 'Splitting light with a prism', 'Measuring the speed of light'],
        x: 'The photoelectric effect only makes sense if light arrives in packets (photons). The double-slit experiment shows wave-like behaviour.' },
      { el: null, q: 'Why can visible light not ionise DNA, while some UV light can?',
        a: 'Visible photons have too little energy to remove an electron', w: ['Visible light is absorbed by the skin', 'UV light travels faster', 'DNA only absorbs radio waves'],
        x: 'Guanine needs 780 kJ mol<sup>−1</sup>, which means wavelengths of 153 nm or shorter (UV-C). Visible light (400–700 nm) falls well short.' },

      // Hydrogen spectrum and energy levels
      { el: 'H', q: 'Excited hydrogen atoms emit light only at certain frequencies. What does this tell us?',
        a: 'Only certain energy levels are allowed: the energy is quantised', w: ['Hydrogen atoms can hold any amount of energy', 'Hydrogen only emits visible light', 'The electron is stationary'],
        x: 'Each line is one transition between two allowed levels, and the photon energy exactly matches the gap.' },
      { el: null, q: 'In the Bohr model, the quantum number n can be…',
        a: 'any positive whole number: 1, 2, 3…', w: ['any number, including fractions', '0, 1 or 2 only', 'any whole number, positive or negative'],
        x: 'Only certain orbits are allowed, numbered n = 1, 2, 3 and so on. n = 1 is the ground state.' },
      { el: 'H', q: 'How does the spacing between hydrogen\'s energy levels change as n increases?',
        a: 'The levels get closer together', w: ['The levels get further apart', 'The spacing stays the same', 'The levels swap order'],
        x: 'That is why the lines in each series crowd together at high frequency and merge into a continuum.' },
      { el: 'H', q: 'Why are the Lyman lines (ending at n = 1) in the ultraviolet?',
        a: 'The drop to n = 1 is the biggest energy gap, so the photons have the most energy', w: ['n = 1 is the highest energy level', 'Lyman lines involve two electrons', 'Ultraviolet light is emitted more slowly'],
        x: 'The gap between n = 1 and n = 2 is much larger than any gap above it, so every transition ending at n = 1 gives a high-energy UV photon.' },
      { el: null, q: 'In an energy-level diagram, the energy of level n = ∞ is considered to be zero. So the other levels have energies that are…',
        a: 'negative', w: ['positive', 'all zero', 'equal to n'],
        x: 'A bound electron has less energy than a free one. Hydrogen\'s levels run from −1312 kJ mol<sup>−1</sup> (n = 1) up towards 0.' },
      { el: 'H', q: 'What is the ionisation energy of hydrogen?',
        a: '1312 kJ mol<sup>−1</sup>', w: ['328 kJ mol<sup>−1</sup>', '656 kJ mol<sup>−1</sup>', '0 kJ mol<sup>−1</sup>'],
        x: 'It is the energy to move the electron from n = 1 to n = ∞: 0 − (−1312) = 1312 kJ mol<sup>−1</sup>, or 2.18 × 10<sup>−18</sup> J per atom.' },
      { el: 'H', q: 'Which equation describes ionising a hydrogen atom?',
        a: 'H → H<sup>+</sup> + e<sup>−</sup>', w: ['H + e<sup>−</sup> → H<sup>−</sup>', 'H<sub>2</sub> → 2H', 'H<sup>+</sup> + e<sup>−</sup> → H'],
        x: 'Removing the electron entirely leaves a bare proton, H<sup>+</sup>.' },

      // Emission and absorption
      { el: null, q: 'Compared with its emission spectrum, an element\'s absorption spectrum has lines at…',
        a: 'the same frequencies: they are the same transitions in reverse', w: ['completely different frequencies', 'half the frequencies', 'only the lowest frequency'],
        x: 'Absorption moves an electron up a gap; emission moves it down the same gap. Same gap, same photon energy.' },
      { el: null, q: 'What does an absorption spectrum look like?',
        a: 'Dark lines on a bright background', w: ['Bright lines on a dark background', 'A continuous rainbow with no gaps', 'A single bright line'],
        x: 'A continuum of light passes through the sample and only the wavelengths that match transitions are removed.' },
      { el: null, q: 'Sunlight has very sharp "missing" wavelengths in its spectrum. What causes them?',
        a: 'Atoms in the Sun\'s outer layers absorb those specific wavelengths', w: ['The Earth\'s magnetic field', 'Gaps in the Sun\'s surface', 'Light slowing down in space'],
        x: 'Each element absorbs only at its own transition energies, so the dark lines are fingerprints of the elements present.' },
      { el: null, q: 'Why do different elements give different flame colours?',
        a: 'Each element has its own set of energy levels, so different transitions', w: ['Different elements burn at different temperatures', 'Heavier atoms emit redder light', 'The flame colour comes from the anion'],
        x: 'Different energy gaps mean photons of different energies, so different colours. You will see this in the Week 3 flame tests.' },
      { el: null, q: 'What does the Bohr model fail to explain?',
        a: 'Atoms with more than one electron', w: ['The hydrogen emission spectrum', 'That energy levels are quantised', 'The Balmer series'],
        x: 'Bohr works for hydrogen but breaks down for multi-electron atoms. What we keep: quantised energy levels described by quantum numbers.' },

      // Flame colours: relating the colour seen to the wavelengths emitted (Week 3 practical)
      { el: 'Na', q: 'In a flame, sodium emits most strongly at 589 nm. What colour does the flame look?',
        a: 'Yellow', w: ['Red', 'Green', 'Violet'],
        x: '589 nm is in the yellow part of the visible spectrum (roughly: violet 400–450, blue 450–490, green 490–560, yellow 560–590, orange 590–620, red 620–700 nm).' },
      { el: 'Li', q: 'Lithium\'s strongest emission line is at 671 nm. What colour does a lithium flame look?',
        a: 'Red', w: ['Yellow', 'Green', 'Blue'],
        x: '671 nm is towards the long-wavelength (red) end of the visible spectrum, so lithium gives a crimson red flame.' },
      { el: 'Ba', q: 'A barium flame emits mostly at wavelengths between about 510 and 555 nm. What colour does it look?',
        a: 'Green', w: ['Red', 'Yellow', 'Violet'],
        x: '510–555 nm is the green part of the visible spectrum, so barium gives a green flame (and green fireworks).' },
      { el: 'K', q: 'Potassium emits at 766 nm (deep red, at the edge of what we can see) and at 404 nm (violet). What colour does a potassium flame look?',
        a: 'Lilac (pale purple)', w: ['Yellow', 'Green', 'Orange'],
        x: 'The eye mixes the two ends of the spectrum: red plus violet looks purple, so potassium gives a faint lilac flame.' },
      { el: 'Sr', q: 'Strontium gives a red flame. Which emission wavelength best explains this?',
        a: '650 nm', w: ['450 nm', '520 nm', '580 nm'],
        x: '650 nm is red light. 450 nm would look blue, 520 nm green and 580 nm yellow.' },
      { el: 'Ca', q: 'Calcium gives an orange-red flame. Around which wavelength is it emitting most strongly?',
        a: '620 nm', w: ['460 nm', '490 nm', '510 nm'],
        x: '620 nm sits between orange and red. The other wavelengths would give blue or green light.' },
      { el: 'Cu', q: 'Copper(II) compounds give a blue-green flame. Around which wavelength is the light mostly emitted?',
        a: '500 nm', w: ['590 nm', '640 nm', '700 nm'],
        x: '500 nm is where blue meets green. 590 nm would look yellow-orange, and 640 and 700 nm red.' },
      { el: ['Li', 'Na'], q: 'Lithium\'s flame emits at 671 nm and sodium\'s at 589 nm. Which element\'s photons carry more energy?',
        a: 'Sodium\'s', w: ['Lithium\'s', 'They are the same', 'You can\'t tell without knowing the brightness'],
        x: 'Shorter wavelength means higher frequency and more energy per photon (E = hc/λ). 589 nm is shorter than 671 nm.' },
    ]
  },

  skills1: {
    title: 'Chemistry Skills 1: Maths for chemists',
    short: 'Skills 1',
    // Generated questions use random numbers, so every student gets different values.
    generators: ['sfWrite', 'sfMulDiv', 'sfAdd', 'prefix', 'cubed', 'sigCount', 'reportMulDiv', 'reportAdd', 'molesEl', 'cv'],
    generalWeight: 6,
    stealGenerators: ['stealMolesEl', 'stealDensityEl', 'stealTitration', 'stealStoich', 'stealPhoton', 'stealHydrate'],
    questions: [
      // Standard form and calculators
      { el: null, q: 'Which is larger, 10<sup>−9</sup> or 10<sup>−12</sup>?',
        a: '10<sup>−9</sup>', w: ['10<sup>−12</sup>', 'They are equal', 'It depends on the units'],
        x: '10<sup>−9</sup> is 0.000 000 001 and 10<sup>−12</sup> is 0.000 000 000 001, so 10<sup>−9</sup> is a thousand times larger.' },
      { el: null, q: 'In standard form, a × 10<sup>n</sup>, what values can a take?',
        a: '1 ≤ a < 10', w: ['0 < a < 1', '1 ≤ a < 100', 'Any whole number'],
        x: 'The number in front is from 1 up to (but not including) 10, and n is a whole number, positive or negative.' },
      { el: null, q: 'Typing 3.00 × 10 ^ 8 ÷ 4.57 × 10 ^ 14 into a calculator gives 6.56 × 10<sup>21</sup>, not 6.56 × 10<sup>−7</sup>. Why?',
        a: 'It divides by 4.57, then multiplies by 10<sup>14</sup>', w: ['The calculator is in the wrong angle mode', '10 ^ 14 is too large for the calculator', 'Standard form cannot be divided'],
        x: 'Use the ×10<sup>x</sup> key, or put brackets round the whole denominator, so the calculator divides by 4.57 × 10<sup>14</sup> as one number.' },
      { el: null, q: 'The safest way to enter 4.57 × 10<sup>14</sup> on a scientific calculator is…',
        a: '4.57 [×10<sup>x</sup>] 14', w: ['4.57 × 10 ^ 14 with no brackets', '4.57 ^ 14', '4.57 × 14'],
        x: 'The ×10<sup>x</sup> (or EXP) key keeps the number together as one value.' },
      { el: null, q: 'A student calculates the mass of one water molecule. Which answer is realistic?',
        a: '2.99 × 10<sup>−23</sup> g', w: ['2.99 × 10<sup>23</sup> g', '18.02 g', '1.08 × 10<sup>25</sup> g'],
        x: '18.02 g mol<sup>−1</sup> ÷ 6.022 × 10<sup>23</sup> mol<sup>−1</sup> = 2.99 × 10<sup>−23</sup> g. 2.99 × 10<sup>23</sup> g would be heavier than Mount Everest.' },
      { el: null, q: 'Which is a realistic frequency for green light (550 nm)?',
        a: '5.45 × 10<sup>14</sup> Hz', w: ['545 kHz', '5.45 × 10<sup>5</sup> Hz', '1.65 × 10<sup>17</sup> Hz'],
        x: 'ν = c/λ = 3.00 × 10<sup>8</sup> ÷ 5.50 × 10<sup>−7</sup> m. 545 kHz comes from forgetting to convert nm to m, and is an AM radio frequency.' },
      { el: null, q: 'Before pressing any calculator keys, what habit catches most exponent errors?',
        a: 'Estimate the power of ten of the answer', w: ['Round every input to 1 s.f.', 'Work in decimals rather than standard form', 'Repeat the calculation twice the same way'],
        x: 'A quick estimate tells you roughly what to expect, so an answer out by a factor of 10<sup>28</sup> stands out immediately.' },

      // Units
      { el: null, q: 'Which SI base unit already contains a prefix?',
        a: 'The kilogram', w: ['The metre', 'The mole', 'The kelvin'],
        x: 'The kilogram is the only SI base unit with a prefix built in, so energy in joules needs mass in kg, not g.' },
      { el: null, q: 'Which of these is the same as 1 L?',
        a: '1 dm<sup>3</sup>', w: ['1 m<sup>3</sup>', '1 cm<sup>3</sup>', '100 cm<sup>3</sup>'],
        x: '1 L = 1 dm<sup>3</sup> = 1000 cm<sup>3</sup> = 0.001 m<sup>3</sup>. So mol L<sup>−1</sup> and mol dm<sup>−3</sup> are the same unit.' },
      { el: null, q: 'In biochemistry, a concentration written as "0.10 M" means…',
        a: '0.10 mol dm<sup>−3</sup>', w: ['0.10 mol m<sup>−3</sup>', '0.10 mega-moles', '0.10 mg per mL'],
        x: 'M is shorthand for mol dm<sup>−3</sup> (mol L<sup>−1</sup>).' },
      { el: null, q: 'The prefixes m (milli) and M (mega) differ by a factor of…',
        a: '10<sup>9</sup>', w: ['10<sup>3</sup>', '10<sup>6</sup>', '1: they mean the same'],
        x: 'milli is 10<sup>−3</sup> and mega is 10<sup>6</sup>. Prefix symbols are case sensitive.' },
      { el: null, q: '1 µL is equal to…',
        a: '10<sup>−3</sup> mL', w: ['10<sup>−6</sup> mL', '10<sup>3</sup> mL', '10<sup>−3</sup> L'],
        x: '1 µL = 10<sup>−6</sup> L = 10<sup>−3</sup> mL (= 1 mm<sup>3</sup>). Micropipettes such as the P200 are labelled in µL.' },
      { el: null, q: 'Which prefix is 10<sup>−12</sup>, used for bond lengths?',
        a: 'pico (p)', w: ['nano (n)', 'micro (µ)', 'femto (f)'],
        x: 'Bond lengths are typically tens to hundreds of pm, for example 74 pm for H<sub>2</sub>.' },
      { el: null, q: 'A temperature change of 1 °C is the same as a change of…',
        a: '1 K', w: ['273.15 K', '274.15 K', '−272.15 K'],
        x: 'The degree Celsius and the kelvin are the same size; only the zero point differs (0 °C = 273.15 K). Absolute temperatures in equations must be in kelvin.' },
      { el: null, q: 'One ångström (Å) is…',
        a: '10<sup>−10</sup> m', w: ['10<sup>−9</sup> m', '10<sup>−12</sup> m', '10<sup>−6</sup> m'],
        x: '1 Å = 10<sup>−10</sup> m = 0.1 nm = 100 pm.' },
      { el: null, q: '1 cm<sup>3</sup> is how many m<sup>3</sup>?',
        a: '10<sup>−6</sup> m<sup>3</sup>', w: ['10<sup>−2</sup> m<sup>3</sup>', '10<sup>−3</sup> m<sup>3</sup>', '10<sup>6</sup> m<sup>3</sup>'],
        x: '1 cm = 10<sup>−2</sup> m, so 1 cm<sup>3</sup> = (10<sup>−2</sup> m)<sup>3</sup> = 10<sup>−6</sup> m<sup>3</sup>. The conversion factor is cubed too.' },
      { el: null, q: 'Gold has a density of 19.3 g cm<sup>−3</sup>. What is that in kg m<sup>−3</sup>?',
        a: '1.93 × 10<sup>4</sup> kg m<sup>−3</sup>', w: ['1.93 kg m<sup>−3</sup>', '1.93 × 10<sup>−2</sup> kg m<sup>−3</sup>', '1.93 × 10<sup>7</sup> kg m<sup>−3</sup>'],
        x: '× (1 kg / 1000 g) × (10<sup>6</sup> cm<sup>3</sup> / 1 m<sup>3</sup>). Using 10<sup>2</sup> instead of 10<sup>6</sup> gives 1.93 kg m<sup>−3</sup>: a cubic metre of gold weighing as much as a bag of sugar.' },
      { el: null, q: 'The molar absorption coefficient ε has units mol<sup>−1</sup> dm<sup>3</sup> cm<sup>−1</sup>. Why is dm<sup>3</sup> on the top line?',
        a: 'Dividing by a concentration (mol dm<sup>−3</sup>) puts dm<sup>3</sup> on top', w: ['Because ε is a volume', 'It is a typing convention with no meaning', 'Because the cuvette is 1 dm long'],
        x: 'Units come from the calculation that produces the quantity. Dividing by mol dm<sup>−3</sup> gives mol<sup>−1</sup> dm<sup>3</sup>.' },
      { el: null, q: 'Enzyme specific activity has units of µmol min<sup>−1</sup> mg<sup>−1</sup>. Which formula fits? (n = product formed, t = time, m = enzyme mass)',
        a: 'n / (t × m)', w: ['n × t / m', 'm / (n × t)', 'n × m / t'],
        x: 'µmol is on top, so an amount goes on top. min<sup>−1</sup> and mg<sup>−1</sup> are negative powers, so time and mass both go underneath.' },
      { el: null, q: 'Using n = m/M with m in g and M in g mol<sup>−1</sup>, what are the units of n?',
        a: 'mol', w: ['g<sup>2</sup> mol<sup>−1</sup>', 'mol<sup>−1</sup>', 'g mol'],
        x: 'g ÷ g mol<sup>−1</sup> = mol. If the units of your answer are not what you wanted, you have rearranged something incorrectly.' },
      { el: null, q: 'In E = hν, h is in J s and ν in s<sup>−1</sup>. What are the units of E?',
        a: 'J', w: ['J s<sup>2</sup>', 'J s<sup>−1</sup>', 's<sup>−1</sup>'],
        x: 'J s × s<sup>−1</sup> = J. Units are a free check on your algebra.' },
      { el: null, q: 'To find ν from c = λν, you should calculate…',
        a: 'ν = c / λ', w: ['ν = cλ', 'ν = λ / c', 'ν = c − λ'],
        x: 'Divide both sides by λ. Check with units: m s<sup>−1</sup> ÷ m = s<sup>−1</sup>.' },

      // Significant figures and precision
      { el: null, q: 'How many significant figures does "1500 g" have?',
        a: 'You can\'t tell: it could be 2, 3 or 4', w: ['2', '4', '0'],
        x: 'Trailing zeros in a whole number are ambiguous. Standard form removes the doubt: 1.5 × 10<sup>3</sup>, 1.50 × 10<sup>3</sup> or 1.500 × 10<sup>3</sup> g.' },
      { el: null, q: '0.0230 has how many significant figures and how many decimal places?',
        a: '3 s.f. and 4 d.p.', w: ['4 s.f. and 4 d.p.', '3 s.f. and 3 d.p.', '5 s.f. and 4 d.p.'],
        x: 'Leading zeros never count as significant figures, but the trailing zero after the decimal point does.' },
      { el: null, q: 'n = cV = 0.10 mol dm<sup>−3</sup> × 0.02357 dm<sup>3</sup>. The calculator shows 0.002357. How should n be reported?',
        a: '2.4 × 10<sup>−3</sup> mol', w: ['2.357 × 10<sup>−3</sup> mol', '2 × 10<sup>−3</sup> mol', '0.002357 mol'],
        x: 'When multiplying, keep the fewest significant figures of the inputs: 0.10 has 2 s.f.' },
      { el: null, q: 'Reporting a result as 2.4 × 10<sup>−3</sup> mol tells the reader the true value is probably between…',
        a: '2.35 and 2.45 × 10<sup>−3</sup> mol', w: ['2.3565 and 2.3575 × 10<sup>−3</sup> mol', '1.5 and 2.5 × 10<sup>−3</sup> mol', '2.0 and 3.0 × 10<sup>−3</sup> mol'],
        x: 'The number of figures you quote communicates how much tolerance to put around the value.' },
      { el: null, q: 'A dinosaur skeleton was "70 million years old" twelve years ago. Why is "70 million and twelve years" wrong?',
        a: 'Adding a precise number cannot make an imprecise one more precise', w: ['Twelve years is too short to measure', 'Ages must be in standard form', 'You can only add numbers with the same units'],
        x: 'The uncertainty is millions of years. When adding or subtracting, keep the fewest decimal places (here, the least precise place value).' },
      { el: null, q: 'Subtracting 25.5 cm<sup>3</sup> from 29.2 cm<sup>3</sup> gives 3.7 cm<sup>3</sup>. What has happened to the precision?',
        a: 'Still 1 d.p., but only 2 s.f.: subtracting similar numbers loses significant figures', w: ['It gains a significant figure', 'Nothing: it is still 3 s.f.', 'It becomes exact'],
        x: 'A ±0.1 cm<sup>3</sup> reading error is small next to 29.2 but large next to 3.7. That is why a bigger sample gives a better density.' },
      { el: null, q: 'In a formula like 2AgNO<sub>3</sub> + MgCl<sub>2</sub> → …, does the "2" limit the significant figures of your answer?',
        a: 'No: stoichiometric numbers are exact', w: ['Yes: it has 1 s.f.', 'Yes: it has 2 s.f.', 'Only when multiplying'],
        x: 'Exact numbers (counts, stoichiometries, defined constants) have unlimited significant figures.' },
      { el: null, q: 'To get a more precise final answer, which measurement should you improve first?',
        a: 'The least precise one', w: ['The most precise one', 'The largest one', 'The one measured last'],
        x: 'Your answer is only as good as your worst measurement.' },

      // Multi-step calculations
      { el: null, q: 'To find the energy of one mole of 280 nm photons, what is the first step?',
        a: 'Convert 280 nm to metres', w: ['Multiply by N<sub>A</sub>', 'Calculate E = hν', 'Divide by h'],
        x: 'Plan backwards (J mol<sup>−1</sup> ← E × N<sub>A</sub> ← E = hν ← ν = c/λ ← λ in m), then work forwards starting with the unit conversion.' },
      { el: null, q: 'Rounding each step of the 280 nm calculation to 2 s.f. gives 4.4 × 10<sup>5</sup> J mol<sup>−1</sup> instead of 4.28 × 10<sup>5</sup>. What is the lesson?',
        a: 'Keep values in the calculator and round only at the end', w: ['Always use 2 s.f.', 'Round to 1 s.f. instead', 'The constants are wrong'],
        x: 'Rounding errors build up along a chain. Carry results forward with Ans or the memory; write values down, but do not retype them.' },
      { el: null, q: 'What is the energy of one mole of 280 nm photons? (the chain from the lecture)',
        a: '428 kJ mol<sup>−1</sup>', w: ['7.10 × 10<sup>−19</sup> kJ mol<sup>−1</sup>', '0.428 kJ mol<sup>−1</sup>', '4.28 × 10<sup>8</sup> kJ mol<sup>−1</sup>'],
        x: 'ν = 1.071 × 10<sup>15</sup> s<sup>−1</sup>; E = 7.10 × 10<sup>−19</sup> J per photon; × 6.022 × 10<sup>23</sup> = 4.28 × 10<sup>5</sup> J mol<sup>−1</sup> = 428 kJ mol<sup>−1</sup>.' },

      // Amount of substance
      { el: null, q: 'For n = cV with c in mol dm<sup>−3</sup>, V must be in…',
        a: 'dm<sup>3</sup>', w: ['mL', 'cm<sup>3</sup>', 'm<sup>3</sup>'],
        x: 'The volume unit must match the concentration unit. 9.85 mL = 9.85 × 10<sup>−3</sup> dm<sup>3</sup>.' },
      { el: null, q: 'A student works out moles in 9.85 mL of 0.0100 M AgNO<sub>3</sub> as 0.01 × 9.85 = 0.0985 mol. What went wrong?',
        a: 'The volume wasn\'t converted to dm<sup>3</sup>: the answer is 1000 times too big', w: ['Nothing: 0.0985 mol is right', 'M should have been converted to mol m<sup>−3</sup>', 'They should have divided instead of multiplied'],
        x: 'n = 0.0100 mol dm<sup>−3</sup> × 9.85 × 10<sup>−3</sup> dm<sup>3</sup> = 9.85 × 10<sup>−5</sup> mol.' },
      { el: null, q: '2AgNO<sub>3</sub> + MgCl<sub>2</sub>·6H<sub>2</sub>O → 2AgCl + … If 9.85 × 10<sup>−5</sup> mol AgNO<sub>3</sub> reacted, how much MgCl<sub>2</sub>·6H<sub>2</sub>O was present?',
        a: '4.93 × 10<sup>−5</sup> mol', w: ['1.97 × 10<sup>−4</sup> mol', '9.85 × 10<sup>−5</sup> mol', '5.91 × 10<sup>−4</sup> mol'],
        x: '2 mol AgNO<sub>3</sub> react with 1 mol MgCl<sub>2</sub>·6H<sub>2</sub>O, so divide by 2.' },
      { el: null, q: 'Why must the "·6H<sub>2</sub>O" be included in the molar mass of MgCl<sub>2</sub>·6H<sub>2</sub>O?',
        a: 'Six water molecules are part of every formula unit', w: ['It is only there to show the salt is wet', 'Water has no mass on the atomic scale', 'It only matters for concentrations'],
        x: 'MgCl<sub>2</sub>·6H<sub>2</sub>O is 203.31 g mol<sup>−1</sup>; MgCl<sub>2</sub> alone is 95.21. Leaving the water out sends an identification to the wrong answer.' },
      { el: null, q: 'In the chloride titration, Ag<sup>+</sup> + Cl<sup>−</sup> → AgCl. For a group 2 chloride XCl<sub>2</sub>, moles of salt are…',
        a: 'half the moles of Ag<sup>+</sup> used', w: ['equal to the moles of Ag<sup>+</sup> used', 'twice the moles of Ag<sup>+</sup> used', 'impossible to find'],
        x: 'Each Ag<sup>+</sup> removes one Cl<sup>−</sup>, and each XCl<sub>2</sub> supplies two Cl<sup>−</sup>.' },
      { el: null, q: 'The titration gives M = 0.10 ÷ 4.93 × 10<sup>−4</sup> = 202.8… g mol<sup>−1</sup>. With 0.10 g and 0.10 mol dm<sup>−3</sup>, how should it be reported?',
        a: '2.0 × 10<sup>2</sup> g mol<sup>−1</sup>', w: ['202.8 g mol<sup>−1</sup>', '203 g mol<sup>−1</sup>', '200.0 g mol<sup>−1</sup>'],
        x: 'The mass and concentration are both known to only 2 s.f., so the answer is 2 s.f. Standard form shows that clearly.' },
    ]
  },

  isotopes: {
    title: 'The atom, isotopes and relative mass',
    short: 'Atoms 1',
    generators: ['neutrons', 'protons', 'notation', 'ions', 'ram', 'abundance', 'mono'],
    // Harder numeric challenges used when stealing an element from the other team
    stealGenerators: ['stealRam', 'stealPeaks', 'stealAbundance', 'stealDiatomic'],
    questions: [

      // ---------- General questions (can appear on any element) ----------
      { el: null, q: 'Isotopes of the same element have the same number of ___ but a different number of ___.',
        a: 'protons; neutrons', w: ['neutrons; protons', 'electrons; protons', 'protons; electrons'],
        x: 'The number of protons (atomic number) defines the element. Isotopes differ only in their number of neutrons, and so in mass.' },
      { el: null, q: 'Which number tells you which element an atom is?',
        a: 'The atomic number (number of protons)', w: ['The mass number', 'The number of neutrons', 'The relative atomic mass'],
        x: 'Every atom with 6 protons is carbon, whatever its neutron count. Change the proton number and you change the element.' },
      { el: null, q: 'The mass number of an atom is equal to…',
        a: 'protons + neutrons', w: ['protons + electrons', 'neutrons only', 'protons only'],
        x: 'Protons and neutrons (nucleons) each have a mass of about 1 u; electrons contribute almost nothing.' },
      { el: null, q: 'Two isotopes of the same element will generally…',
        a: 'react in the same way chemically, but differ slightly in mass', w: ['have different chemical properties', 'have different numbers of electrons in the neutral atom', 'sit in different places on the periodic table'],
        x: 'Chemistry is governed by electrons. Isotopes have the same number of protons, so the same number of electrons in the neutral atom, and the same chemistry.' },
      { el: null, q: 'The relative atomic mass printed on the periodic table is…',
        a: 'an abundance-weighted average of the masses of the naturally occurring isotopes', w: ['the mass of the most common isotope', 'the simple average of all known isotopes', 'the number of protons plus neutrons in one atom'],
        x: 'It is a weighted mean, which is why chlorine is 35.45 even though no single chlorine atom has that mass.' },
      { el: null, q: 'Relative atomic mass (A<sub>r</sub>) has units of…',
        a: 'none: it is a ratio', w: ['grams', 'g mol<sup>−1</sup>', 'kilograms per atom'],
        x: 'A<sub>r</sub> compares the average atomic mass with 1/12 of the mass of a <sup>12</sup>C atom, so the units cancel. Molar mass (g mol<sup>−1</sup>) has the same number but does have units.' },
      { el: null, q: 'One dalton (1 Da, also written 1 u) is defined as…',
        a: '1/12 of the mass of a <sup>12</sup>C atom', w: ['the mass of one proton exactly', 'the mass of one hydrogen atom exactly', '1/16 of the mass of an <sup>16</sup>O atom'],
        x: 'The unified atomic mass unit and the dalton are the same thing: 1/12 of the mass of a carbon-12 atom.' },
      { el: null, q: 'Hen egg-white lysozyme has a mass of about 14.3 kDa. In daltons, that is…',
        a: '14,300 Da', w: ['1,430 Da', '143,000 Da', '14.3 Da'],
        x: 'k means 10<sup>3</sup>, so 14.3 kDa = 14,300 Da. Protein masses are nearly always quoted in kDa.' },
      { el: null, q: 'Which of these would change if you swapped an atom for a heavier isotope of the same element?',
        a: 'The mass of the atom', w: ['The number of protons', 'The charge on the nucleus', 'The number of electrons in the neutral atom'],
        x: 'Only the neutron count changes, so only the mass changes. Nuclear charge, and therefore electron count, stay the same.' },
      { el: null, q: 'A sample from a different source has a slightly different relative atomic mass for the same element. The best explanation is…',
        a: 'its isotopic composition is different', w: ['its atoms contain a different number of protons', 'it has been weighed less accurately', 'its atoms have lost electrons'],
        x: 'Relative atomic mass is a property of a sample, not a constant of nature. Change the mix of isotopes and the weighted average changes.' },

      // ---------- Element-linked questions ----------
      { el: 'H', q: 'Deuterium (<sup>2</sup>H) is an isotope of hydrogen. How many neutrons does a deuterium atom contain?',
        a: '1', w: ['0', '2', '3'], x: 'Mass number 2 minus 1 proton leaves 1 neutron. Ordinary hydrogen, <sup>1</sup>H, has none.' },
      { el: 'H', q: 'Compared with an ordinary <sup>1</sup>H atom, a tritium (<sup>3</sup>H) atom has…',
        a: 'two extra neutrons', w: ['two extra protons', 'two extra electrons', 'one extra proton and one extra neutron'],
        x: 'All hydrogen isotopes have one proton. Tritium has mass number 3, so it carries two neutrons.' },
      { el: 'H', q: 'Biochemists run NMR spectra in solvents such as D<sub>2</sub>O and CDCl<sub>3</sub>. What is the "D"?',
        a: 'Deuterium, the hydrogen isotope <sup>2</sup>H', w: ['Dysprosium', 'A hydrogen ion, H<sup>+</sup>', 'Tritium, <sup>3</sup>H'],
        x: 'Deuterium behaves chemically like hydrogen but does not show up in a <sup>1</sup>H NMR spectrum, so the solvent does not swamp the sample.' },

      { el: 'He', q: 'Helium-3 and helium-4 differ in their number of…',
        a: 'neutrons', w: ['protons', 'electrons', 'protons and electrons'],
        x: 'Both have 2 protons (that is what makes them helium). <sup>3</sup>He has 1 neutron and <sup>4</sup>He has 2.' },

      { el: 'C', q: 'Carbon\'s relative atomic mass is 12.011, just above 12. What does that tell you?',
        a: 'A small fraction of carbon atoms are heavier than <sup>12</sup>C', w: ['Every carbon atom has a mass of 12.011 u', 'Some carbon atoms have 7 protons', 'Electrons add 0.011 u to each atom'],
        x: 'About 1.1% of carbon is <sup>13</sup>C, which pulls the weighted average slightly above 12.' },
      { el: 'C', q: 'The atomic mass unit is defined relative to which isotope?',
        a: '<sup>12</sup>C', w: ['<sup>1</sup>H', '<sup>16</sup>O', '<sup>13</sup>C'],
        x: '1 u (1 Da) is exactly 1/12 of the mass of a carbon-12 atom.' },

      { el: 'N', q: 'Meselson and Stahl grew <i>E. coli</i> on <sup>15</sup>N to show that DNA replication is semiconservative. How does <sup>15</sup>N differ from <sup>14</sup>N?',
        a: 'It has one more neutron', w: ['It has one more proton', 'It has one more electron', 'It is radioactive'],
        x: '<sup>15</sup>N is a stable isotope with 8 neutrons rather than 7. Same chemistry, slightly heavier.' },
      { el: 'N', q: 'Why could Meselson and Stahl separate DNA made with <sup>15</sup>N from DNA made with <sup>14</sup>N?',
        a: '<sup>15</sup>N-DNA is denser', w: ['<sup>15</sup>N-DNA is radioactive', '<sup>15</sup>N-DNA base-pairs differently', '<sup>15</sup>N-DNA carries more negative charge'],
        x: 'The extra neutrons make the DNA slightly denser, so heavy, hybrid and light DNA settle at different positions in a caesium chloride density gradient.' },

      { el: 'Ne', q: 'Neon is roughly 90% <sup>20</sup>Ne and 10% <sup>22</sup>Ne. Estimate its relative atomic mass.',
        a: '20.2', w: ['21.0', '21.8', '20.0'],
        x: '(0.90 × 20) + (0.10 × 22) = 18.0 + 2.2 = 20.2. The real value is 20.18.' },
      { el: 'Cl', q: 'Chlorine\'s relative atomic mass is 35.45, yet no chlorine atom has a mass of 35.45 u. Why?',
        a: 'It is an abundance-weighted average of <sup>35</sup>Cl and <sup>37</sup>Cl', w: ['Chlorine atoms have half a neutron on average', 'Electrons add 0.45 u', 'It is the simple average of 35 and 37, rounded'],
        x: 'About 76% <sup>35</sup>Cl and 24% <sup>37</sup>Cl gives a weighted average of 35.5. The simple average (36) would be wrong.' },
      { el: 'Cl', q: 'In a mass spectrum, a molecule containing one Cl atom shows peaks at M and M+2 in a ratio of roughly…',
        a: '3 : 1', w: ['1 : 1', '1 : 3', '9 : 1'],
        x: 'Roughly three quarters of chlorine atoms are <sup>35</sup>Cl and one quarter <sup>37</sup>Cl.' },
      { el: 'Ar', q: 'Argon (A<sub>r</sub> 39.95) comes before potassium (A<sub>r</sub> 39.10) in the periodic table even though it is heavier. Why?',
        a: 'The table is ordered by atomic number, not mass', w: ['Argon\'s mass was measured wrongly', 'Noble gases are always placed first', 'Potassium has more neutrons'],
        x: 'Argon has 18 protons and potassium 19. Argon\'s high mass comes from its abundance of the heavy isotope <sup>40</sup>Ar.' },
      { el: 'Ar', q: 'Most argon on Earth is <sup>40</sup>Ar, made by decay of <sup>40</sup>K in rocks. Argon from elsewhere in the Solar System has a quite different A<sub>r</sub>. This shows that…',
        a: 'relative atomic mass depends on where the sample came from', w: ['argon atoms on other planets have more protons', 'A<sub>r</sub> values on the periodic table are wrong', 'isotopes have different chemistry'],
        x: 'A<sub>r</sub> is a property of a sample. Different histories give different isotope mixtures.' },

      { el: 'U', q: 'Why can\'t <sup>235</sup>U and <sup>238</sup>U be separated by an ordinary chemical reaction?',
        a: 'Isotopes have the same electron arrangement, so the same chemistry', w: ['Uranium is chemically unreactive', 'They have different numbers of protons', 'They are both radioactive'],
        x: 'Chemistry depends on electrons. Separating isotopes needs a method that exploits their small mass difference instead.' },
    ]
  },

  // Questions beyond Lecture 1 and A-level (applications, radioactivity, history).
  // Not used unless you set topic: 'isotopesExtension' or copy them into another bank.
  isotopesExtension: {
    title: 'Isotopes: applications and extension',
    short: 'Isotope extras',
    generators: [],
    questions: [
      { el: 'C', q: 'Radiocarbon dating measures how much of which isotope is left in a sample?',
        a: '<sup>14</sup>C', w: ['<sup>12</sup>C', '<sup>13</sup>C', '<sup>11</sup>C'],
        x: 'Living things take in <sup>14</sup>C with their carbon. After death it decays away with a half-life of about 5,730 years, so what remains dates the sample.' },
      { el: 'C', q: '<sup>14</sup>C has a half-life of about 5,730 years. What fraction of the original <sup>14</sup>C is left after about 11,460 years?',
        a: 'One quarter', w: ['One half', 'None', 'One eighth'],
        x: '11,460 years is two half-lives: ½ × ½ = ¼.' },
      { el: 'O', q: 'In 1941 Ruben and Kamen gave plants water labelled with <sup>18</sup>O and found the label in the O<sub>2</sub> they released. What did this show?',
        a: 'The O<sub>2</sub> from photosynthesis comes from water', w: ['The O<sub>2</sub> from photosynthesis comes from CO<sub>2</sub>', 'Plants absorb O<sub>2</sub> through their roots', '<sup>18</sup>O is radioactive'],
        x: 'Using a heavy but stable isotope as a tracer let them follow oxygen atoms from water to oxygen gas.' },

      { el: 'F', q: 'The PET tracer <sup>18</sup>F-FDG accumulates in tissues with a high metabolic rate, such as many tumours. FDG is an analogue of…',
        a: 'glucose', w: ['ATP', 'cholesterol', 'haemoglobin'],
        x: 'Fluorodeoxyglucose is taken up like glucose. Fluorine-18 has a half-life of about 110 minutes, long enough to scan but short enough to keep the dose low.' },

      { el: 'Ne', q: 'In 1913 J.J. Thomson found that neon gave two traces in his apparatus, at masses 20 and 22. This was early evidence that…',
        a: 'stable elements can exist as more than one isotope', w: ['neon is radioactive', 'neon forms Ne<sub>2</sub> molecules', 'atoms can gain protons'],
        x: 'Neon was the first stable (non-radioactive) element shown to have isotopes.' },

      { el: 'P', q: 'In the Hershey–Chase experiment, <sup>32</sup>P was used to label the bacteriophage\'s…',
        a: 'DNA', w: ['protein coat', 'lipid membrane', 'tail fibres only'],
        x: 'DNA has a phosphate backbone, while protein contains little phosphorus. The <sup>32</sup>P went into the bacteria, showing DNA is the genetic material.' },
      { el: 'S', q: 'In the Hershey–Chase experiment, <sup>35</sup>S was used to label protein. Why sulfur?',
        a: 'Protein contains sulfur (in Cys and Met) but DNA does not', w: ['DNA contains sulfur but protein does not', 'Sulfur is the most abundant element in protein', 'Sulfur binds only to DNA'],
        x: 'Each label marked one kind of molecule. The <sup>35</sup>S stayed outside the bacteria with the empty phage coats.' },

      { el: 'Br', q: 'In a mass spectrum, a molecule containing one Br atom shows peaks at M and M+2 in a ratio of roughly…',
        a: '1 : 1', w: ['3 : 1', '1 : 3', '9 : 1'],
        x: 'Bromine is about 51% <sup>79</sup>Br and 49% <sup>81</sup>Br, so the two peaks are almost equal in height.' },

      { el: 'K', q: 'Bananas are very slightly radioactive because of the potassium they contain. Which isotope is responsible?',
        a: '<sup>40</sup>K', w: ['<sup>39</sup>K', '<sup>41</sup>K', '<sup>38</sup>K'],
        x: 'About 0.012% of natural potassium is <sup>40</sup>K, which has a half-life of about 1.25 billion years.' },

      { el: 'Sr', q: 'Strontium-90 from nuclear fallout builds up in bones and teeth. Why?',
        a: 'Strontium is in the same group as calcium and behaves chemically like it', w: ['<sup>90</sup>Sr has the same mass as calcium', 'Bones absorb any radioactive element', 'Strontium replaces phosphorus in DNA'],
        x: 'Isotope identity sets the radioactivity; group membership sets the chemistry. The body treats Sr<sup>2+</sup> much like Ca<sup>2+</sup>.' },

      { el: 'Tc', q: 'Technetium-99m is the most widely used isotope in medical imaging. Which statement about technetium is true?',
        a: 'It has no stable isotopes', w: ['It is the most abundant metal in the Earth\'s crust', 'All its isotopes have 43 neutrons', 'It is a noble gas'],
        x: 'Technetium (Z = 43) is the lightest element with no stable isotope, which is why hospitals make it on site from a molybdenum-99 generator.' },
      { el: 'Mo', q: 'Hospitals produce technetium-99m from a "generator" containing which parent isotope?',
        a: '<sup>99</sup>Mo', w: ['<sup>98</sup>Mo', '<sup>99</sup>Ru', '<sup>100</sup>Mo'],
        x: 'Molybdenum-99 decays to technetium-99m. Same mass number, but Z goes up by one, from 42 to 43.' },
      { el: 'Pm', q: 'Promethium and technetium share an unusual property among the elements lighter than lead. What is it?',
        a: 'They have no stable isotopes', w: ['They are both gases', 'They have only one electron shell', 'They each have exactly one isotope'],
        x: 'Every isotope of Tc (Z = 43) and Pm (Z = 61) is radioactive. All other elements up to lead have at least one stable isotope.' },

      { el: 'Sn', q: 'Tin holds the record for the most stable isotopes of any element. How many?',
        a: '10', w: ['3', '6', '21'],
        x: 'Tin (Z = 50) has ten stable isotopes, from <sup>112</sup>Sn to <sup>124</sup>Sn.' },
      { el: 'I', q: 'Radioactive iodine-131 is used to treat an overactive thyroid gland. Why does it end up in the thyroid?',
        a: 'The thyroid takes up iodine to make thyroid hormones', w: ['<sup>131</sup>I is attracted by the thyroid\'s magnetic field', 'The thyroid absorbs any radioactive substance', 'Iodine-131 binds only to thyroid DNA'],
        x: 'The body cannot tell <sup>131</sup>I from stable <sup>127</sup>I, so the radioactive isotope follows iodine\'s normal route.' },
      { el: 'Cs', q: 'The SI second is defined using the radiation from a transition in which atom?',
        a: '<sup>133</sup>Cs', w: ['<sup>12</sup>C', '<sup>86</sup>Kr', '<sup>1</sup>H'],
        x: 'Since 1967 the second has been defined by exactly 9,192,631,770 cycles of radiation from caesium-133, the element\'s only stable isotope.' },
      { el: 'Kr', q: 'From 1960 to 1983 the metre was defined using light emitted by which isotope?',
        a: '<sup>86</sup>Kr', w: ['<sup>133</sup>Cs', '<sup>40</sup>Ar', '<sup>20</sup>Ne'],
        x: 'An orange-red line of krypton-86 defined the metre until it was redefined via the speed of light.' },

      { el: 'Pb', q: 'The relative atomic mass of lead varies noticeably between samples from different mines. Why?',
        a: 'Three of its isotopes are end products of uranium and thorium decay, so the mix depends on the rock\'s history', w: ['Lead atoms gain protons over time', 'Lead is weighed differently in different countries', 'Lead\'s electrons are easily lost'],
        x: '<sup>206</sup>Pb, <sup>207</sup>Pb and <sup>208</sup>Pb build up from decay of U and Th, so older or uranium-rich rocks give lead with a different isotope mix.' },
      { el: 'Bi', q: 'Bismuth-209 was found in 2003 to decay, with a half-life of about 2 × 10<sup>19</sup> years. The universe is about 1.4 × 10<sup>10</sup> years old. The half-life is roughly…',
        a: 'a billion times the age of the universe', w: ['a thousand times the age of the universe', 'about the same as the age of the universe', 'a million times shorter than the age of the universe'],
        x: '2 × 10<sup>19</sup> ÷ 1.4 × 10<sup>10</sup> ≈ 1.4 × 10<sup>9</sup>, so about a billion times longer. For all practical purposes bismuth is stable.' },
      { el: 'Rn', q: 'Parts of Devon and Cornwall have high levels of radon-222 in homes. Where does it come from?',
        a: 'Decay of uranium in granite', w: ['Car exhausts', 'Sea spray', 'Cosmic rays hitting the atmosphere'],
        x: 'Radon-222 is part of the uranium-238 decay chain. Granite is relatively rich in uranium, and radon, being a gas, seeps into buildings.' },
      { el: 'Ra', q: 'Radium-226 (Z = 88) decays by emitting an alpha particle (a <sup>4</sup>He nucleus). What does it become?',
        a: '<sup>222</sup>Rn (Z = 86)', w: ['<sup>222</sup>Ra (Z = 88)', '<sup>226</sup>Rn (Z = 86)', '<sup>224</sup>Rn (Z = 86)'],
        x: 'Losing 2 protons and 2 neutrons takes the mass number down by 4 and Z down by 2, turning radium into radon.' },
      { el: 'U', q: 'Natural uranium is 99.3% <sup>238</sup>U and 0.7% <sup>235</sup>U. When uranium is "enriched" for fuel, what changes?',
        a: 'The proportion of <sup>235</sup>U increases', w: ['Extra protons are added to each atom', 'The uranium is converted into plutonium', 'The atoms gain electrons'],
        x: 'Enrichment changes the isotope mix of the sample, not the atoms themselves.' },
      { el: 'Pu', q: 'NASA\'s Curiosity rover on Mars is powered by heat from the decay of which isotope?',
        a: '<sup>238</sup>Pu', w: ['<sup>235</sup>U', '<sup>14</sup>C', '<sup>60</sup>Co'],
        x: 'Plutonium-238 has a half-life of about 88 years, giving steady heat for decades. Voyager 1 and 2 use it too.' },
      { el: 'Am', q: 'Many household smoke alarms contain a tiny amount of which isotope?',
        a: '<sup>241</sup>Am', w: ['<sup>222</sup>Rn', '<sup>131</sup>I', '<sup>90</sup>Sr'],
        x: 'Americium-241 ionises the air in a small chamber; smoke disrupts the current and triggers the alarm.' },

    ]
  },

  // Copy this block to make a bank for another lecture.
  template: {
    title: 'My next lecture',
    generators: [],
    questions: [
      { el: null, q: 'A general question that can appear on any element?', a: 'Right answer', w: ['Wrong 1', 'Wrong 2', 'Wrong 3'], x: 'Why the right answer is right.' },
      { el: 'Na', q: 'A question that only appears when someone taps sodium?', a: 'Right answer', w: ['Wrong 1', 'Wrong 2', 'Wrong 3'], x: 'Explanation.' },
    ]
  }
};
