// Periodic Table Quest question set: Atoms lecture 3: electrons as waves, orbitals and quantum numbers.
// The file name (without .js) is this set's id. See _template.js for how to write one.
PQ.questionSet({
  title: 'Atoms 3: Orbitals and quantum numbers',
  short: 'Atoms 3',
  generators: ['a3Exists', 'a3Subshell', 'a3Shell', 'a3Values', 'a3Name', 'a3Angular', 'a3Config'],
  generalWeight: 5,
  stealGenerators: ['s3Electrons', 's3Orbitals', 's3Psi'],
  questions: [

    // ---------- Electrons as waves ----------
    { el: null, q: 'Which observation shows that a beam of electrons behaves as a wave?',
      a: 'Electron diffraction: the beam gives an interference pattern', w: ['Electrons are deflected by a magnet', 'Electrons carry a negative charge', 'Electrons are ejected from metals by UV light'],
      x: 'Diffraction and interference (constructive and destructive) are wave behaviours. A stream of electrons shows them, just as light does.' },
    { el: null, q: 'The wavelengths of electron beams are typically similar to…',
      a: 'the lengths of bonds between atoms', w: ['the wavelength of visible light', 'the width of a human hair', 'the size of an atomic nucleus'],
      x: 'Because the wavelengths are comparable to bond lengths, electron diffraction can be used to measure bond lengths in molecules.' },
    { el: 'C', q: 'C<sub>60</sub> "buckyball" molecules have been shown to diffract. What does this demonstrate?',
      a: 'Even large molecules show wave-like behaviour', w: ['Carbon atoms have no mass', 'Only charged particles behave as waves', 'C<sub>60</sub> molecules are smaller than electrons'],
      x: 'In theory any moving object has a wavelength. C<sub>60</sub> is among the largest objects in which wave behaviour has been observed experimentally.' },
    { el: null, q: 'An electron held in an atom behaves as a standing wave. Why does this lead to quantised energy levels?',
      a: 'Only certain wavelengths fit around the atom', w: ['The electron slows down as it orbits', 'The nucleus absorbs some wavelengths', 'Standing waves have no energy'],
      x: 'The wave has to join up with itself all the way round. Only some wavelengths do this, and each allowed pattern corresponds to a value of n and an energy.' },
    { el: null, q: 'Which statement best describes an electron in an atom?',
      a: 'It exists as the whole wave around the atom at once, more in some places than others', w: ['It follows a circular path around the nucleus', 'It sits still at a fixed distance from the nucleus', 'It jumps between fixed points on a circle'],
      x: 'Diagrams of standing waves are not pictures of the electron\'s path. The wave is the electron.' },

    // ---------- Wavefunctions, probability and electron density ----------
    { el: null, q: 'What is an electron\'s wavefunction, ψ?',
      a: 'A mathematical function that gives a value at every point in space around the nucleus', w: ['The path the electron follows around the nucleus', 'The energy needed to remove the electron', 'The speed of the electron at each moment'],
      x: 'Feed in a position (x, y, z) and the wavefunction gives out a number. In the lecture, ψ(0.1, 0.2, 0.1) = 0.44 for hydrogen\'s 1s electron.' },
    { el: null, q: 'A wavefunction can be positive in one region and negative in another. What does the sign tell you?',
      a: 'The phase of the wave in that region', w: ['Whether the electron is there or not', 'The charge of the electron there', 'Whether that region is inside or outside the atom'],
      x: 'Positive and negative regions are out of phase with each other. The sign matters when orbitals combine to form bonds.' },
    { el: null, q: 'The probability of finding an electron in a small region is proportional to…',
      a: 'ψ² (the wavefunction squared)', w: ['ψ', '√ψ', '1/ψ'],
      x: 'Squaring removes the sign: |ψ|² is always positive or zero, as a probability must be.' },
    { el: null, q: 'At one point ψ = +0.4 and at another ψ = −0.4. How do the chances of finding the electron at the two points compare?',
      a: 'They are equal', w: ['It is more likely at the +0.4 point', 'It is more likely at the −0.4 point', 'The electron can\'t be at the −0.4 point'],
      x: 'Probability depends on ψ², and (+0.4)² = (−0.4)² = 0.16. The sign is phase, not likelihood.' },
    { el: null, q: 'Can we work out exactly where an electron is at a particular moment?',
      a: 'No: we can only find the probability of it being in a region', w: ['Yes, from its wavefunction', 'Yes, if we know its energy', 'Only for the 1s orbital'],
      x: 'It is fundamentally impossible to pin down an electron\'s position. The best we can do is a probability, for example 12% that it is inside a particular cube.' },
    { el: null, q: 'Can electron density ever be negative?',
      a: 'No: it is always positive or zero', w: ['Yes, wherever ψ is negative', 'Yes, at a node', 'Only in p orbitals'],
      x: 'Electron density follows ψ², which is never negative, even where ψ itself is negative. Unlike ψ, density has no phase.' },
    { el: null, q: 'An orbital is drawn as a "balloon" (boundary surface). Is the electron contained inside that surface?',
      a: 'No: the surface marks an arbitrary value of ψ, and the wavefunction extends beyond it', w: ['Yes: the electron cannot leave the surface', 'Yes, but only in the ground state', 'No: the electron is only ever on the surface itself'],
      x: 'The lecture\'s example used a threshold of ±0.5. Choosing ±0.25 would give bigger balloons for the same orbital. Wavefunctions approach zero far from the nucleus but never reach a hard edge.' },
    { el: null, q: 'What are the two main things you can get from an atom\'s wavefunction?',
      a: 'Where the electron is likely to be, and its energy', w: ['Its charge and its mass', 'Its speed and its direction of travel', 'Its age and its spin'],
      x: 'The wavefunction gives the probability distribution (so electron density) and the electron\'s energy.' },

    // ---------- Quantum numbers ----------
    { el: null, q: 'Why is there no 1p orbital?',
      a: 'For n = 1, l can only be 0, which is an s orbital', w: ['1p orbitals exist but are too high in energy', 'p orbitals can only hold one electron', 'The 1p orbital is the same as 2s'],
      x: 'l can be any whole number from 0 to n − 1. For n = 1 that is just l = 0 (s).' },
    { el: null, q: 'Which letter is used for an orbital with l = 2?',
      a: 'd', w: ['p', 'f', 's'],
      x: 's, p, d and f stand for l = 0, 1, 2 and 3.' },
    { el: null, q: 'What does the principal quantum number n mostly tell you about an orbital?',
      a: 'Its energy level and how far it extends from the nucleus', w: ['Its shape', 'Its orientation in space', 'The direction of the electron\'s spin'],
      x: 'Higher n means a higher energy level and a more spread-out wavefunction. Shape is set by l and orientation by m<sub>l</sub>.' },
    { el: null, q: 'Which quantum number sets the shape of an orbital (s, p, d, f)?',
      a: 'l, the secondary quantum number', w: ['n, the principal quantum number', '<i>m</i><sub>l</sub>, the magnetic quantum number', '<i>m</i><sub>s</sub>, the spin quantum number'],
      x: 'l gives the subshell letter and so the shape. <i>m</i><sub>l</sub> picks out the individual orbitals within it, such as the three 2p orbitals.' },

    // ---------- Shapes and nodes ----------
    { el: null, q: 'What is an angular node (nodal plane)?',
      a: 'A plane through the nucleus where ψ = 0, so the electron is never found there', w: ['The point where the electron is most likely to be', 'The outer edge of the orbital', 'A plane where ψ is largest'],
      x: 'On one side of the plane ψ is positive and on the other negative. Because ψ varies smoothly, it must pass through zero at the plane.' },
    { el: null, q: 'In a 2p<sub>z</sub> orbital, how do the two lobes above and below the xy plane differ?',
      a: 'They have opposite signs of ψ (opposite phases)', w: ['One contains the electron and the other doesn\'t', 'One is much larger than the other', 'They are identical in every way'],
      x: 'ψ is positive above the xy plane and negative below it, with a nodal plane between. ψ² is the same shape in both lobes.' },

    // ---------- Radial distribution functions ----------
    { el: null, q: 'What does a radial distribution function (RDF) show?',
      a: 'How likely the electron is to be found at a given distance from the nucleus, in any direction', w: ['The shape of the orbital', 'How the electron\'s energy changes with time', 'The sign of the wavefunction at each point'],
      x: 'The peak of the RDF is the most likely distance. Larger n puts the peak further out.' },
    { el: 'H', q: 'At about what distance from the nucleus is the peak of hydrogen\'s 1s radial distribution function?',
      a: '53 pm', w: ['0 pm', '5.3 pm', '530 pm'],
      x: 'The peak, about 53 pm, is the most likely distance. The RDF is zero at the nucleus itself.' },
    { el: null, q: 'Which has the greater chance of being found very close to the nucleus?',
      a: 'A 2s electron', w: ['A 2p electron', 'They are the same', 'Neither: both have zero probability close to the nucleus'],
      x: 'The 2s RDF has a small inner hump close to the nucleus; 2p has none. Next lecture uses this to explain why 2s is lower in energy than 2p.' },

    // ---------- Energy levels and building up atoms ----------
    { el: 'H', q: 'In a one-electron atom such as hydrogen, how do the energies of the 2s and 2p orbitals compare?',
      a: 'They are the same (degenerate)', w: ['2s is lower', '2p is lower', '2p doesn\'t exist in hydrogen'],
      x: 'With only one electron, the energy depends only on n, proportional to −1/n².' },
    { el: null, q: 'In atoms with more than one electron, how do the 2s and 2p subshells compare in energy?',
      a: '2s is lower than 2p', w: ['They are the same', '2p is lower than 2s', '2s is higher than 3s'],
      x: 'With more than one electron, the subshells within a shell split apart in energy. Next lecture explains why.' },
    { el: null, q: 'What does the Pauli exclusion principle say?',
      a: 'No two electrons in an atom may have exactly the same set of quantum numbers', w: ['Electrons always fill the highest orbital first', 'Each orbital can hold any number of electrons', 'Electrons in the same atom must have the same spin'],
      x: 'This is why electrons can\'t all crowd into 1s: each orbital takes at most two, with opposite spins.' },
    { el: 'He', q: 'Helium has two electrons in its 1s orbital. How can that satisfy the Pauli exclusion principle?',
      a: 'They have different spin quantum numbers, +½ and −½', w: ['They have different values of n', 'One is in a 1p orbital', 'The principle doesn\'t apply to helium'],
      x: 'Both have n = 1, l = 0, m<sub>l</sub> = 0. The fourth quantum number, <i>m</i><sub>s</sub>, differs: one ↑ (+½), one ↓ (−½).' },
    { el: null, q: 'What values can the spin quantum number <i>m</i><sub>s</sub> take?',
      a: '+½ or −½', w: ['0 or 1', '−1, 0 or +1', 'Any value from −l to +l'],
      x: 'Spin has only two directions, drawn as ↑ (+½) and ↓ (−½).' },
    { el: 'Li', q: 'Why does lithium\'s third electron go into the 2s orbital?',
      a: 'The 1s orbital is full (one ↑ and one ↓), and 2s is the next lowest in energy', w: ['2s is lower in energy than 1s', 'Lithium has no 1s orbital', 'Electrons always go into the largest orbital'],
      x: 'Pauli allows only two electrons in 1s. The next one goes into the lowest-energy orbital with a vacancy, which is 2s.' },
    { el: 'Li', q: 'Which set of quantum numbers could describe lithium\'s outermost (2s) electron?',
      a: 'n = 2, l = 0, <i>m</i><sub>l</sub> = 0, <i>m</i><sub>s</sub> = +½', w: ['n = 1, l = 0, <i>m</i><sub>l</sub> = 0, <i>m</i><sub>s</sub> = +½', 'n = 2, l = 1, <i>m</i><sub>l</sub> = 0, <i>m</i><sub>s</sub> = +½', 'n = 2, l = 0, <i>m</i><sub>l</sub> = 1, <i>m</i><sub>s</sub> = +½'],
      x: '2s means n = 2 and l = 0, so <i>m</i><sub>l</sub> can only be 0. The first option is 1s, the third is 2p, and the fourth isn\'t allowed because <i>m</i><sub>l</sub> can\'t exceed l.' },
    { el: 'He', q: 'Why is helium\'s 1s orbital lower in energy than hydrogen\'s?',
      a: 'Helium\'s nucleus has a greater positive charge', w: ['Helium has more neutrons', 'Helium\'s 1s orbital holds more electrons', 'Helium is a noble gas'],
      x: 'As the nuclear charge increases, the "same" orbitals become smaller and lower in energy.' },
    { el: null, q: 'In the configuration 1s<sup>2</sup> 2s<sup>1</sup>, what does the superscript 2 mean?',
      a: 'Two electrons are in the 1s subshell', w: ['The 1s orbital is squared', 'It is the second shell', 'There are two 1s orbitals'],
      x: '1s<sup>2</sup> 2s<sup>1</sup> (lithium) means two electrons in 1s and one in 2s.' },
  ]
});
