// Periodic Table Quest question set: Atoms lecture 4: building atoms and the periodic table.
// The file name (without .js) is this set's id. See _template.js for how to write one.
PQ.questionSet({
  title: 'Atoms 4: Building atoms and the periodic table',
  short: 'Atoms 4',
  generators: ['a4Config', 'a4Short', 'a4Which', 'a4Unpaired', 'a4Group', 'a4Lower', 'a4Bigger', 'a4IE', 'a4Displace'],
  generalWeight: 4,
  stealGenerators: ['s4Count', 's4Halogen', 's4IEatom'],
  questions: [

    // ---------- Why subshells split: shielding, penetration, effective nuclear charge ----------
    { el: null, q: 'In a many-electron atom, what is the order of the subshells in a shell, from lowest to highest energy?',
      a: 's, p, d, f', w: ['f, d, p, s', 'They all have the same energy', 'p, s, d, f'],
      x: 'In hydrogen they are degenerate. With more than one electron they split, with s lowest, then p, then d, then f.' },
    { el: 'He', q: 'He<sup>+</sup> and H both have one electron in 1s. Why is the He<sup>+</sup> electron lower in energy?',
      a: 'Helium\'s nucleus has a +2 charge, so the electron is attracted more strongly', w: ['He<sup>+</sup> has more neutrons', 'He<sup>+</sup> has a second electron to shield it', 'Its 1s orbital is bigger'],
      x: 'The greater the effective charge of the nucleus felt by an electron, the closer and lower in energy its orbital.' },
    { el: null, q: 'What is shielding?',
      a: 'Electrons closer to the nucleus repel an outer electron, cancelling some of the nucleus\'s attraction', w: ['The nucleus repelling its own electrons', 'Outer electrons protecting the nucleus from radiation', 'Electrons in the same orbital cancelling each other\'s spin'],
      x: 'Shielding reduces the effective nuclear charge that an outer electron feels.' },
    { el: 'Li', q: 'Lithium\'s nucleus has a +3 charge, but its 2s electron feels an effective nuclear charge of only about +1.3. Why?',
      a: 'The two 1s electrons sit mostly closer to the nucleus and shield it', w: ['The 2s electron shields itself', 'Lithium\'s neutrons cancel some of the charge', 'The 2s electron is outside the atom'],
      x: 'The point is not the exact number but that it is much less than +3: the two 1s electrons cancel most of the nucleus\'s pull.' },
    { el: null, q: 'Why is 2s lower in energy than 2p in a many-electron atom?',
      a: '2s penetrates closer to the nucleus, so it feels a greater effective nuclear charge', w: ['2s can hold more electrons', '2p is further from the nucleus at its main peak', '2s electrons are not shielded at all'],
      x: 'The small inner hump of the 2s radial distribution function puts some 2s density very close to the nucleus, inside most of the 1s electrons, where it feels more of the nuclear charge.' },
    { el: null, q: 'The main peak of the 2p radial distribution function (about 210 pm) is actually closer to the nucleus than the main 2s peak (about 280 pm). So what makes 2s more penetrating?',
      a: 'The small inner hump of 2s, very close to the nucleus', w: ['The main 2s peak', 'The nodal plane of 2p', 'Nothing: 2p is more penetrating'],
      x: 'It is the inner hump, not the main peak, that lets a 2s electron spend some time inside the 1s electrons and feel more of the nucleus.' },
    { el: 'Na', q: 'Sodium has electrons in its third shell. Which order is correct for the energies of its n = 3 subshells?',
      a: '3s < 3p < 3d', w: ['3s = 3p = 3d', '3d < 3p < 3s', '3p < 3s < 3d'],
      x: 's orbitals are the most penetrating, so an s electron feels the most nuclear charge; d orbitals are the least penetrating.' },

    // ---------- Building atoms: Hund's rule ----------
    { el: null, q: 'What does Hund\'s rule say?',
      a: 'Electrons occupy orbitals of the same energy singly, with parallel spins, before any pairing', w: ['Each orbital holds at most two electrons', 'Electrons fill the lowest-energy orbitals first', 'Electrons in the same orbital have the same spin'],
      x: 'The other two rules are real too, but they are Pauli (two per orbital) and the aufbau idea (lowest energy first).' },
    { el: 'C', q: 'Carbon has two 2p electrons. How are they arranged in its ground state?',
      a: 'In two different 2p orbitals, with parallel spins', w: ['Paired in the same 2p orbital', 'In two different 2p orbitals, with opposite spins', 'One in 2p and one in 3s'],
      x: 'Hund\'s rule: singly, with parallel spins. The other arrangements are possible but higher in energy.' },
    { el: 'N', q: 'How many unpaired electrons does a nitrogen atom have?',
      a: '3', w: ['1', '2', '0'],
      x: 'Nitrogen is 1s<sup>2</sup> 2s<sup>2</sup> 2p<sup>3</sup>: one electron in each 2p orbital, all with parallel spins.' },
    { el: 'O', q: 'Oxygen (1s<sup>2</sup> 2s<sup>2</sup> 2p<sup>4</sup>) is the first atom in which…',
      a: 'two 2p electrons have to pair up in the same orbital', w: ['a 2p electron appears', 'the n = 2 shell is full', 'a 3s electron appears'],
      x: 'Three 2p electrons go in singly; the fourth must pair up.' },
    { el: 'B', q: 'Boron (1s<sup>2</sup> 2s<sup>2</sup> 2p<sup>1</sup>) is the first atom to…',
      a: 'have an electron in a 2p orbital', w: ['have a full n = 2 shell', 'have a 2s electron', 'need Hund\'s rule to place its electrons'],
      x: 'Lithium and beryllium fill 2s; boron\'s fifth electron starts on 2p.' },
    { el: 'Ne', q: 'Neon (1s<sup>2</sup> 2s<sup>2</sup> 2p<sup>6</sup>) completes the n = 2 shell. What follows from this?',
      a: 'Neon is very unreactive, and sodium starts a new row of the periodic table', w: ['Neon is very reactive', 'Sodium\'s next electron goes into 2d', 'Neon has two unpaired electrons'],
      x: 'With 2s and 2p both full, the next electron (sodium\'s) has to go into 3s, the start of a new shell and a new period.' },

    // ---------- Shorthand, core and valence ----------
    { el: null, q: 'In a shorthand configuration such as [Ne] 3s<sup>1</sup>, which electrons are the valence electrons?',
      a: 'Those outside the noble-gas core: here the 3s electron', w: ['Those in the [Ne] core', 'All of them', 'Only the electrons in 1s'],
      x: 'Core electrons are arranged like the previous noble gas. Valence electrons are the ones outside it, and are far more likely to take part in reactions.' },
    { el: null, q: 'Why do elements in the same group of the periodic table behave alike?',
      a: 'They have the same valence configuration', w: ['They have the same number of electrons', 'They have the same atomic mass', 'They have the same number of shells'],
      x: 'Li [He] 2s<sup>1</sup>, Na [Ne] 3s<sup>1</sup> and K [Ar] 4s<sup>1</sup>: same outer arrangement, similar chemistry.' },
    { el: 'K', q: 'After argon you might expect 3d to fill next. Why does potassium\'s outer electron go into 4s instead?',
      a: '4s is penetrating enough to be marginally lower in energy than 3d', w: ['3d orbitals don\'t exist until n = 4', '4s holds more electrons than 3d', 'Hund\'s rule forbids 3d'],
      x: 'So K is [Ar] 4s<sup>1</sup> and Ca is [Ar] 4s<sup>2</sup>. 3d fills next, in the transition metals.' },
    { el: 'Ca', q: 'What is the shorthand configuration of calcium?',
      a: '[Ar] 4s<sup>2</sup>', w: ['[Ar] 3d<sup>2</sup>', '[Ne] 3s<sup>2</sup>', '[Ar] 4s<sup>1</sup> 3d<sup>1</sup>'],
      x: '4s is marginally below 3d, so calcium\'s last two electrons both go into 4s.' },

    // ---------- Shape of the periodic table ----------
    { el: null, q: 'Why is the d-block of the periodic table 10 elements wide?',
      a: 'A d subshell has 5 orbitals, each holding 2 electrons', w: ['There are 10 d orbitals in each shell', 'd orbitals have 10 angular nodes', 'It is a historical convention'],
      x: 'Block widths match subshell capacities: s 2, p 6, d 10, f 14.' },
    { el: null, q: 'How wide is the p-block of the periodic table?',
      a: '6 elements', w: ['3 elements', '8 elements', '10 elements'],
      x: 'A p subshell has 3 orbitals, each holding 2 electrons, so 6.' },

    // ---------- Periodic trends ----------
    { el: null, q: 'Across a period atoms gain electrons, yet they get smaller. Why?',
      a: 'Electrons in the same shell shield each other poorly, so the effective nuclear charge rises', w: ['The extra electrons are in a lower shell', 'Electrons repel each other less as they are added', 'The nucleus gets physically larger'],
      x: 'Each step adds a proton and an electron to the same shell. Inner-shell electrons shield well; same-shell electrons don\'t, so the outer electrons are pulled in closer.' },
    { el: ['C', 'F'], q: 'Carbon\'s 2p electrons feel an effective nuclear charge of about +2.9, fluorine\'s about +5.2. Which atom is smaller?',
      a: 'Fluorine', w: ['Carbon', 'They are the same size', 'You can\'t tell'],
      x: 'Same subshell, greater pull from the nucleus, so fluorine\'s electrons are held closer: F 64 pm, C 77 pm.' },
    { el: null, q: 'Ionisation energy is the energy needed for which process?',
      a: 'X → X<sup>+</sup> + e<sup>−</sup>', w: ['X + e<sup>−</sup> → X<sup>−</sup>', 'X<sup>+</sup> + e<sup>−</sup> → X', 'X<sub>2</sub> → 2X'],
      x: 'It always takes energy, so ionisation energies are positive, usually in kJ mol<sup>−1</sup>.' },
    { el: 'Na', q: 'Where is the biggest drop in first ionisation energy as you go along the periodic table?',
      a: 'Straight after each noble gas, e.g. from neon to sodium', w: ['Straight before each noble gas', 'In the middle of each period', 'Between the two elements in period 1'],
      x: 'Sodium\'s outer electron starts a new shell (3s), further out and well shielded by the full n = 2 shell, so it is easy to remove.' },

    // ---------- Electron gain energies and halogens ----------
    { el: null, q: 'Electron gain energy refers to which process?',
      a: 'X + e<sup>−</sup> → X<sup>−</sup>', w: ['X → X<sup>+</sup> + e<sup>−</sup>', 'X<sup>−</sup> → X + e<sup>−</sup>', 'X<sub>2</sub> + 2e<sup>−</sup> → 2X'],
      x: 'Usually exothermic, so electron gain energies are usually negative. The bigger the negative number, the more favourable.' },
    { el: ['Cl', 'I'], q: 'Electron gain energies: Cl −349, Br −325, I −295 kJ mol<sup>−1</sup>. Why is adding an electron to iodine less favourable than adding one to chlorine?',
      a: 'Iodine is the biggest atom, so the added electron is held furthest from the nucleus', w: ['Iodine has the most protons', 'Iodine\'s 5p subshell is already full', 'Iodine is a solid'],
      x: 'Chlorine (99 pm) holds the new electron close to the nucleus and low in energy; iodine (133 pm) holds it further away.' },
    { el: 'I', q: 'Which halogen, Cl<sub>2</sub>, Br<sub>2</sub> or I<sub>2</sub>, displaces neither of the other two halides?',
      a: 'I<sub>2</sub>', w: ['Cl<sub>2</sub>', 'Br<sub>2</sub>', 'All three displace each other'],
      x: 'Iodine gains an electron least favourably (−295 kJ mol<sup>−1</sup>), so it can\'t take electrons from bromide or chloride. This matches Experiment B.' },
  ]
});
