// Periodic Table Quest question set: Atoms lecture 2: electromagnetic radiation and energy levels.
// The file name (without .js) is this set's id. See _template.js for how to write one.
PQ.questionSet({
  title: 'Atoms 2: Electromagnetic radiation and energy levels',
  short: 'Atoms 2',
  generators: ['a2Freq', 'a2Lambda', 'a2Energy', 'a2Radio', 'a2Missing', 'a2Region', 'a2Highest', 'a2Photo', 'a2Gap', 'a2IonCompare', 'a2IonLambda'],
  generalWeight: 5,
  stealGenerators: ['s2IonLambda', 's2Line', 's2Kinetic', 's2Radio', 'stealPhoton'],
  questions: [
    // Waves and the spectrum
    { el: null, q: 'Wavelength and frequency are inversely proportional for electromagnetic radiation. Why?',
      a: 'All electromagnetic radiation travels at the same speed, c', w: ['Longer waves carry more energy', 'Photons slow down as frequency rises', 'Frequency and wavelength are measured in the same units'],
      x: 'c = λν with c fixed, so if more waves pass each second (higher ν), each wave must be shorter (smaller λ).' },
    { el: null, q: 'Which list is in order of increasing energy per photon?',
      a: 'Radio, infrared, visible, ultraviolet', w: ['Ultraviolet, visible, infrared, radio', 'Visible, radio, ultraviolet, infrared', 'Infrared, radio, visible, ultraviolet'],
      x: 'Energy per photon rises with frequency (E = hν), so it rises as wavelength falls: radio < microwave < infrared < visible < UV < X-rays.' },
    { el: null, q: 'NMR spectroscopy uses radio waves. What transitions does it involve?',
      a: 'Between nuclear spin levels in a magnetic field', w: ['Between electronic energy levels', 'Between molecular vibrational states', 'Ejection of core electrons'],
      x: 'Radio photons have very little energy, enough only for the tiny gaps between nuclear spin levels.' },
    { el: null, q: 'UV-visible spectroscopy probes transitions between…',
      a: 'electronic energy levels', w: ['nuclear spin levels', 'vibrational states', 'rotational states'],
      x: 'UV and visible photons have enough energy to move electrons between energy levels, which is also why atoms give coloured flames.' },

    // Photons and the photoelectric effect
    { el: 'K', q: 'Very bright visible light shines on potassium metal, but no electrons are ejected. Why not?',
      a: 'Each photon has too little energy, however many there are', w: ['The light is not bright enough yet', 'Potassium has no loosely held electrons', 'Visible light cannot reach a metal surface'],
      x: 'Brighter light means more photons per second, not more energy per photon. Ionisation needs each photon to carry enough energy on its own.' },
    { el: 'K', q: 'Shining UV light on potassium ejects electrons, but only above a threshold frequency of about…',
      a: '5 × 10<sup>14</sup> s<sup>−1</sup>', w: ['5 × 10<sup>8</sup> s<sup>−1</sup>', '5 × 10<sup>20</sup> s<sup>−1</sup>', '5 × 10<sup>−14</sup> s<sup>−1</sup>'],
      x: 'Below about 5 × 10<sup>14</sup> s<sup>−1</sup> (wavelength around 600 nm) each photon carries less than the 3.5 × 10<sup>−19</sup> J needed per atom.' },
    { el: null, q: 'Doubling the intensity of a beam of light, without changing its colour, doubles…',
      a: 'the number of photons per second', w: ['the energy of each photon', 'the frequency of the light', 'the wavelength of the light'],
      x: 'Intensity is the rate of photons. The energy of each photon depends only on its frequency, E = hν.' },
    { el: null, q: 'When a photon has more energy than is needed to eject an electron, the excess energy…',
      a: 'becomes the kinetic energy of the ejected electron', w: ['is re-emitted as a second photon', 'is lost: only the threshold energy is used', 'ejects a second electron'],
      x: 'In the lecture, 250 nm light on potassium has about 4.5 × 10<sup>−19</sup> J left over, which the electron carries away as kinetic energy.' },
    { el: null, q: 'Which experiment shows light behaving as a stream of particles?',
      a: 'The photoelectric effect', w: ['The double-slit experiment', 'Splitting light with a prism', 'Measuring the speed of light'],
      x: 'The photoelectric effect only makes sense if light arrives in packets (photons). The double-slit experiment shows wave-like behaviour.' },
    { el: null, q: 'Why can visible light not ionise DNA, while some UV light can?',
      a: 'Visible photons have too little energy to remove an electron', w: ['Visible light is absorbed by the skin', 'UV light travels faster', 'DNA only absorbs radio waves'],
      x: 'Guanine needs 780 kJ mol<sup>−1</sup>, which means wavelengths of 153 nm or shorter (UV-C). Visible light (400–700 nm) falls well short.' },

    // Hydrogen spectrum and energy levels
    { el: 'H', q: 'Excited hydrogen atoms emit light only at certain frequencies. What does this tell us?',
      a: 'Only certain energy levels are allowed: the energy is quantised', w: ['Hydrogen atoms can hold any amount of energy', 'Hydrogen only emits visible light', 'The electron is stationary'],
      x: 'Each line is one transition between two allowed levels, and the photon energy exactly matches the gap.' },
    { el: null, q: 'In the Bohr model, the quantum number n can be…',
      a: 'any positive whole number: 1, 2, 3…', w: ['any number, including fractions', '0, 1 or 2 only', 'any whole number, positive or negative'],
      x: 'Only certain orbits are allowed, numbered n = 1, 2, 3 and so on. n = 1 is the ground state.' },
    { el: 'H', q: 'How does the spacing between hydrogen\'s energy levels change as n increases?',
      a: 'The levels get closer together', w: ['The levels get further apart', 'The spacing stays the same', 'The levels swap order'],
      x: 'That is why the lines in each series crowd together at high frequency and merge into a continuum.' },
    { el: 'H', q: 'Why are the Lyman lines (ending at n = 1) in the ultraviolet?',
      a: 'The drop to n = 1 is the biggest energy gap, so the photons have the most energy', w: ['n = 1 is the highest energy level', 'Lyman lines involve two electrons', 'Ultraviolet light is emitted more slowly'],
      x: 'The gap between n = 1 and n = 2 is much larger than any gap above it, so every transition ending at n = 1 gives a high-energy UV photon.' },
    { el: null, q: 'In an energy-level diagram, the energy of level n = ∞ is considered to be zero. So the other levels have energies that are…',
      a: 'negative', w: ['positive', 'all zero', 'equal to n'],
      x: 'A bound electron has less energy than a free one. Hydrogen\'s levels run from −1312 kJ mol<sup>−1</sup> (n = 1) up towards 0.' },
    { el: 'H', q: 'What is the ionisation energy of hydrogen?',
      a: '1312 kJ mol<sup>−1</sup>', w: ['328 kJ mol<sup>−1</sup>', '656 kJ mol<sup>−1</sup>', '0 kJ mol<sup>−1</sup>'],
      x: 'It is the energy to move the electron from n = 1 to n = ∞: 0 − (−1312) = 1312 kJ mol<sup>−1</sup>, or 2.18 × 10<sup>−18</sup> J per atom.' },
    { el: 'H', q: 'Which equation describes ionising a hydrogen atom?',
      a: 'H → H<sup>+</sup> + e<sup>−</sup>', w: ['H + e<sup>−</sup> → H<sup>−</sup>', 'H<sub>2</sub> → 2H', 'H<sup>+</sup> + e<sup>−</sup> → H'],
      x: 'Removing the electron entirely leaves a bare proton, H<sup>+</sup>.' },

    // Emission and absorption
    { el: null, q: 'Compared with its emission spectrum, an element\'s absorption spectrum has lines at…',
      a: 'the same frequencies: they are the same transitions in reverse', w: ['completely different frequencies', 'half the frequencies', 'only the lowest frequency'],
      x: 'Absorption moves an electron up a gap; emission moves it down the same gap. Same gap, same photon energy.' },
    { el: null, q: 'What does an absorption spectrum look like?',
      a: 'Dark lines on a bright background', w: ['Bright lines on a dark background', 'A continuous rainbow with no gaps', 'A single bright line'],
      x: 'A continuum of light passes through the sample and only the wavelengths that match transitions are removed.' },
    { el: null, q: 'Sunlight has very sharp "missing" wavelengths in its spectrum. What causes them?',
      a: 'Atoms in the Sun\'s outer layers absorb those specific wavelengths', w: ['The Earth\'s magnetic field', 'Gaps in the Sun\'s surface', 'Light slowing down in space'],
      x: 'Each element absorbs only at its own transition energies, so the dark lines are fingerprints of the elements present.' },
    { el: null, q: 'Why do different elements give different flame colours?',
      a: 'Each element has its own set of energy levels, so different transitions', w: ['Different elements burn at different temperatures', 'Heavier atoms emit redder light', 'The flame colour comes from the anion'],
      x: 'Different energy gaps mean photons of different energies, so different colours. You will see this in the Week 3 flame tests.' },
    { el: null, q: 'What does the Bohr model fail to explain?',
      a: 'Atoms with more than one electron', w: ['The hydrogen emission spectrum', 'That energy levels are quantised', 'The Balmer series'],
      x: 'Bohr works for hydrogen but breaks down for multi-electron atoms. What we keep: quantised energy levels described by quantum numbers.' },

    // Flame colours: relating the colour seen to the wavelengths emitted (Week 3 practical)
    { el: 'Na', q: 'In a flame, sodium emits most strongly at 589 nm. What colour does the flame look?',
      a: 'Yellow', w: ['Red', 'Green', 'Violet'],
      x: '589 nm is in the yellow part of the visible spectrum (roughly: violet 400–450, blue 450–490, green 490–560, yellow 560–590, orange 590–620, red 620–700 nm).' },
    { el: 'Li', q: 'Lithium\'s strongest emission line is at 671 nm. What colour does a lithium flame look?',
      a: 'Red', w: ['Yellow', 'Green', 'Blue'],
      x: '671 nm is towards the long-wavelength (red) end of the visible spectrum, so lithium gives a crimson red flame.' },
    { el: 'Ba', q: 'A barium flame emits mostly at wavelengths between about 510 and 555 nm. What colour does it look?',
      a: 'Green', w: ['Red', 'Yellow', 'Violet'],
      x: '510–555 nm is the green part of the visible spectrum, so barium gives a green flame (and green fireworks).' },
    { el: 'K', q: 'Potassium emits at 766 nm (deep red, at the edge of what we can see) and at 404 nm (violet). What colour does a potassium flame look?',
      a: 'Lilac (pale purple)', w: ['Yellow', 'Green', 'Orange'],
      x: 'The eye mixes the two ends of the spectrum: red plus violet looks purple, so potassium gives a faint lilac flame.' },
    { el: 'Sr', q: 'Strontium gives a red flame. Which emission wavelength best explains this?',
      a: '650 nm', w: ['450 nm', '520 nm', '580 nm'],
      x: '650 nm is red light. 450 nm would look blue, 520 nm green and 580 nm yellow.' },
    { el: 'Ca', q: 'Calcium gives an orange-red flame. Around which wavelength is it emitting most strongly?',
      a: '620 nm', w: ['460 nm', '490 nm', '510 nm'],
      x: '620 nm sits between orange and red. The other wavelengths would give blue or green light.' },
    { el: 'Cu', q: 'Copper(II) compounds give a blue-green flame. Around which wavelength is the light mostly emitted?',
      a: '500 nm', w: ['590 nm', '640 nm', '700 nm'],
      x: '500 nm is where blue meets green. 590 nm would look yellow-orange, and 640 and 700 nm red.' },
    { el: ['Li', 'Na'], q: 'Lithium\'s flame emits at 671 nm and sodium\'s at 589 nm. Which element\'s photons carry more energy?',
      a: 'Sodium\'s', w: ['Lithium\'s', 'They are the same', 'You can\'t tell without knowing the brightness'],
      x: 'Shorter wavelength means higher frequency and more energy per photon (E = hc/λ). 589 nm is shorter than 671 nm.' },
  ]
});
