// Periodic Table Quest question set: Atoms lecture 1: the atom, isotopes and relative mass.
// The file name (without .js) is this set's id. See _template.js for how to write one.
PQ.questionSet({
  title: 'Atoms 1: the atom, isotopes and relative mass',
  short: 'Atoms 1',
  generators: ['neutrons', 'protons', 'notation', 'ions', 'ram', 'abundance', 'mono'],
  // Harder numeric challenges used when stealing an element from the other team
  stealGenerators: ['stealRam', 'stealPeaks', 'stealAbundance', 'stealDiatomic'],
  questions: [

    // ---------- General questions (can appear on any element) ----------
    { el: null, q: 'Isotopes of the same element have the same number of ___ but a different number of ___.',
      a: 'protons; neutrons', w: ['neutrons; protons', 'electrons; protons', 'protons; electrons'],
      x: 'The number of protons (atomic number) defines the element. Isotopes differ only in their number of neutrons, and so in mass.' },
    { el: null, q: 'Which number tells you which element an atom is?',
      a: 'The atomic number (number of protons)', w: ['The mass number', 'The number of neutrons', 'The relative atomic mass'],
      x: 'Every atom with 6 protons is carbon, whatever its neutron count. Change the proton number and you change the element.' },
    { el: null, q: 'The mass number of an atom is equal to…',
      a: 'protons + neutrons', w: ['protons + electrons', 'neutrons only', 'protons only'],
      x: 'Protons and neutrons (nucleons) each have a mass of about 1 u; electrons contribute almost nothing.' },
    { el: null, q: 'Two isotopes of the same element will generally…',
      a: 'react in the same way chemically, but differ slightly in mass', w: ['have different chemical properties', 'have different numbers of electrons in the neutral atom', 'sit in different places on the periodic table'],
      x: 'Chemistry is governed by electrons. Isotopes have the same number of protons, so the same number of electrons in the neutral atom, and the same chemistry.' },
    { el: null, q: 'The relative atomic mass printed on the periodic table is…',
      a: 'an abundance-weighted average of the masses of the naturally occurring isotopes', w: ['the mass of the most common isotope', 'the simple average of all known isotopes', 'the number of protons plus neutrons in one atom'],
      x: 'It is a weighted mean, which is why chlorine is 35.45 even though no single chlorine atom has that mass.' },
    { el: null, q: 'Relative atomic mass (A<sub>r</sub>) has units of…',
      a: 'none: it is a ratio', w: ['grams', 'g mol<sup>−1</sup>', 'kilograms per atom'],
      x: 'A<sub>r</sub> compares the average atomic mass with 1/12 of the mass of a <sup>12</sup>C atom, so the units cancel. Molar mass (g mol<sup>−1</sup>) has the same number but does have units.' },
    { el: null, q: 'One dalton (1 Da, also written 1 u) is defined as…',
      a: '1/12 of the mass of a <sup>12</sup>C atom', w: ['the mass of one proton exactly', 'the mass of one hydrogen atom exactly', '1/16 of the mass of an <sup>16</sup>O atom'],
      x: 'The unified atomic mass unit and the dalton are the same thing: 1/12 of the mass of a carbon-12 atom.' },
    { el: null, q: 'Hen egg-white lysozyme has a mass of about 14.3 kDa. In daltons, that is…',
      a: '14,300 Da', w: ['1,430 Da', '143,000 Da', '14.3 Da'],
      x: 'k means 10<sup>3</sup>, so 14.3 kDa = 14,300 Da. Protein masses are nearly always quoted in kDa.' },
    { el: null, q: 'Which of these would change if you swapped an atom for a heavier isotope of the same element?',
      a: 'The mass of the atom', w: ['The number of protons', 'The charge on the nucleus', 'The number of electrons in the neutral atom'],
      x: 'Only the neutron count changes, so only the mass changes. Nuclear charge, and therefore electron count, stay the same.' },
    { el: null, q: 'A sample from a different source has a slightly different relative atomic mass for the same element. The best explanation is…',
      a: 'its isotopic composition is different', w: ['its atoms contain a different number of protons', 'it has been weighed less accurately', 'its atoms have lost electrons'],
      x: 'Relative atomic mass is a property of a sample, not a constant of nature. Change the mix of isotopes and the weighted average changes.' },

    // ---------- Element-linked questions ----------
    { el: 'H', q: 'Deuterium (<sup>2</sup>H) is an isotope of hydrogen. How many neutrons does a deuterium atom contain?',
      a: '1', w: ['0', '2', '3'], x: 'Mass number 2 minus 1 proton leaves 1 neutron. Ordinary hydrogen, <sup>1</sup>H, has none.' },
    { el: 'H', q: 'Compared with an ordinary <sup>1</sup>H atom, a tritium (<sup>3</sup>H) atom has…',
      a: 'two extra neutrons', w: ['two extra protons', 'two extra electrons', 'one extra proton and one extra neutron'],
      x: 'All hydrogen isotopes have one proton. Tritium has mass number 3, so it carries two neutrons.' },
    { el: 'H', q: 'Biochemists run NMR spectra in solvents such as D<sub>2</sub>O and CDCl<sub>3</sub>. What is the "D"?',
      a: 'Deuterium, the hydrogen isotope <sup>2</sup>H', w: ['Dysprosium', 'A hydrogen ion, H<sup>+</sup>', 'Tritium, <sup>3</sup>H'],
      x: 'Deuterium behaves chemically like hydrogen but does not show up in a <sup>1</sup>H NMR spectrum, so the solvent does not swamp the sample.' },

    { el: 'He', q: 'Helium-3 and helium-4 differ in their number of…',
      a: 'neutrons', w: ['protons', 'electrons', 'protons and electrons'],
      x: 'Both have 2 protons (that is what makes them helium). <sup>3</sup>He has 1 neutron and <sup>4</sup>He has 2.' },

    { el: 'C', q: 'Carbon\'s relative atomic mass is 12.011, just above 12. What does that tell you?',
      a: 'A small fraction of carbon atoms are heavier than <sup>12</sup>C', w: ['Every carbon atom has a mass of 12.011 u', 'Some carbon atoms have 7 protons', 'Electrons add 0.011 u to each atom'],
      x: 'About 1.1% of carbon is <sup>13</sup>C, which pulls the weighted average slightly above 12.' },
    { el: 'C', q: 'The atomic mass unit is defined relative to which isotope?',
      a: '<sup>12</sup>C', w: ['<sup>1</sup>H', '<sup>16</sup>O', '<sup>13</sup>C'],
      x: '1 u (1 Da) is exactly 1/12 of the mass of a carbon-12 atom.' },

    { el: 'N', q: 'Meselson and Stahl grew <i>E. coli</i> on <sup>15</sup>N to show that DNA replication is semiconservative. How does <sup>15</sup>N differ from <sup>14</sup>N?',
      a: 'It has one more neutron', w: ['It has one more proton', 'It has one more electron', 'It is radioactive'],
      x: '<sup>15</sup>N is a stable isotope with 8 neutrons rather than 7. Same chemistry, slightly heavier.' },
    { el: 'N', q: 'Why could Meselson and Stahl separate DNA made with <sup>15</sup>N from DNA made with <sup>14</sup>N?',
      a: '<sup>15</sup>N-DNA is denser', w: ['<sup>15</sup>N-DNA is radioactive', '<sup>15</sup>N-DNA base-pairs differently', '<sup>15</sup>N-DNA carries more negative charge'],
      x: 'The extra neutrons make the DNA slightly denser, so heavy, hybrid and light DNA settle at different positions in a caesium chloride density gradient.' },

    { el: 'Ne', q: 'Neon is roughly 90% <sup>20</sup>Ne and 10% <sup>22</sup>Ne. Estimate its relative atomic mass.',
      a: '20.2', w: ['21.0', '21.8', '20.0'],
      x: '(0.90 × 20) + (0.10 × 22) = 18.0 + 2.2 = 20.2. The real value is 20.18.' },
    { el: 'Cl', q: 'Chlorine\'s relative atomic mass is 35.45, yet no chlorine atom has a mass of 35.45 u. Why?',
      a: 'It is an abundance-weighted average of <sup>35</sup>Cl and <sup>37</sup>Cl', w: ['Chlorine atoms have half a neutron on average', 'Electrons add 0.45 u', 'It is the simple average of 35 and 37, rounded'],
      x: 'About 76% <sup>35</sup>Cl and 24% <sup>37</sup>Cl gives a weighted average of 35.5. The simple average (36) would be wrong.' },
    { el: 'Cl', q: 'In a mass spectrum, a molecule containing one Cl atom shows peaks at M and M+2 in a ratio of roughly…',
      a: '3 : 1', w: ['1 : 1', '1 : 3', '9 : 1'],
      x: 'Roughly three quarters of chlorine atoms are <sup>35</sup>Cl and one quarter <sup>37</sup>Cl.' },
    { el: 'Ar', q: 'Argon (A<sub>r</sub> 39.95) comes before potassium (A<sub>r</sub> 39.10) in the periodic table even though it is heavier. Why?',
      a: 'The table is ordered by atomic number, not mass', w: ['Argon\'s mass was measured wrongly', 'Noble gases are always placed first', 'Potassium has more neutrons'],
      x: 'Argon has 18 protons and potassium 19. Argon\'s high mass comes from its abundance of the heavy isotope <sup>40</sup>Ar.' },
    { el: 'Ar', q: 'Most argon on Earth is <sup>40</sup>Ar, made by decay of <sup>40</sup>K in rocks. Argon from elsewhere in the Solar System has a quite different A<sub>r</sub>. This shows that…',
      a: 'relative atomic mass depends on where the sample came from', w: ['argon atoms on other planets have more protons', 'A<sub>r</sub> values on the periodic table are wrong', 'isotopes have different chemistry'],
      x: 'A<sub>r</sub> is a property of a sample. Different histories give different isotope mixtures.' },

    { el: 'U', q: 'Why can\'t <sup>235</sup>U and <sup>238</sup>U be separated by an ordinary chemical reaction?',
      a: 'Isotopes have the same electron arrangement, so the same chemistry', w: ['Uranium is chemically unreactive', 'They have different numbers of protons', 'They are both radioactive'],
      x: 'Chemistry depends on electrons. Separating isotopes needs a method that exploits their small mass difference instead.' },
  ]
});
