// Periodic Table Quest question set: Chemistry Skills 1: maths for chemists.
// The file name (without .js) is this set's id. See _template.js for how to write one.
PQ.questionSet({
  title: 'Chemistry Skills 1: Maths for chemists',
  short: 'Skills 1',
  // Generated questions use random numbers, so every student gets different values.
  generators: ['sfWrite', 'sfMulDiv', 'sfAdd', 'prefix', 'cubed', 'sigCount', 'reportMulDiv', 'reportAdd', 'molesEl', 'cv'],
  generalWeight: 6,
  stealGenerators: ['stealMolesEl', 'stealDensityEl', 'stealTitration', 'stealStoich', 'stealPhoton', 'stealHydrate'],
  questions: [
    // Standard form and calculators
    { el: null, q: 'Which is larger, 10<sup>−9</sup> or 10<sup>−12</sup>?',
      a: '10<sup>−9</sup>', w: ['10<sup>−12</sup>', 'They are equal', 'It depends on the units'],
      x: '10<sup>−9</sup> is 0.000 000 001 and 10<sup>−12</sup> is 0.000 000 000 001, so 10<sup>−9</sup> is a thousand times larger.' },
    { el: null, q: 'In standard form, a × 10<sup>n</sup>, what values can a take?',
      a: '1 ≤ a < 10', w: ['0 < a < 1', '1 ≤ a < 100', 'Any whole number'],
      x: 'The number in front is from 1 up to (but not including) 10, and n is a whole number, positive or negative.' },
    { el: null, q: 'Typing 3.00 × 10 ^ 8 ÷ 4.57 × 10 ^ 14 into a calculator gives 6.56 × 10<sup>21</sup>, not 6.56 × 10<sup>−7</sup>. Why?',
      a: 'It divides by 4.57, then multiplies by 10<sup>14</sup>', w: ['The calculator is in the wrong angle mode', '10 ^ 14 is too large for the calculator', 'Standard form cannot be divided'],
      x: 'Use the ×10<sup>x</sup> key, or put brackets round the whole denominator, so the calculator divides by 4.57 × 10<sup>14</sup> as one number.' },
    { el: null, q: 'The safest way to enter 4.57 × 10<sup>14</sup> on a scientific calculator is…',
      a: '4.57 [×10<sup>x</sup>] 14', w: ['4.57 × 10 ^ 14 with no brackets', '4.57 ^ 14', '4.57 × 14'],
      x: 'The ×10<sup>x</sup> (or EXP) key keeps the number together as one value.' },
    { el: null, q: 'A student calculates the mass of one water molecule. Which answer is realistic?',
      a: '2.99 × 10<sup>−23</sup> g', w: ['2.99 × 10<sup>23</sup> g', '18.02 g', '1.08 × 10<sup>25</sup> g'],
      x: '18.02 g mol<sup>−1</sup> ÷ 6.022 × 10<sup>23</sup> mol<sup>−1</sup> = 2.99 × 10<sup>−23</sup> g. 2.99 × 10<sup>23</sup> g would be heavier than Mount Everest.' },
    { el: null, q: 'Which is a realistic frequency for green light (550 nm)?',
      a: '5.45 × 10<sup>14</sup> Hz', w: ['545 kHz', '5.45 × 10<sup>5</sup> Hz', '1.65 × 10<sup>17</sup> Hz'],
      x: 'ν = c/λ = 3.00 × 10<sup>8</sup> ÷ 5.50 × 10<sup>−7</sup> m. 545 kHz comes from forgetting to convert nm to m, and is an AM radio frequency.' },
    { el: null, q: 'Before pressing any calculator keys, what habit catches most exponent errors?',
      a: 'Estimate the power of ten of the answer', w: ['Round every input to 1 s.f.', 'Work in decimals rather than standard form', 'Repeat the calculation twice the same way'],
      x: 'A quick estimate tells you roughly what to expect, so an answer out by a factor of 10<sup>28</sup> stands out immediately.' },

    // Units
    { el: null, q: 'Which SI base unit already contains a prefix?',
      a: 'The kilogram', w: ['The metre', 'The mole', 'The kelvin'],
      x: 'The kilogram is the only SI base unit with a prefix built in, so energy in joules needs mass in kg, not g.' },
    { el: null, q: 'Which of these is the same as 1 L?',
      a: '1 dm<sup>3</sup>', w: ['1 m<sup>3</sup>', '1 cm<sup>3</sup>', '100 cm<sup>3</sup>'],
      x: '1 L = 1 dm<sup>3</sup> = 1000 cm<sup>3</sup> = 0.001 m<sup>3</sup>. So mol L<sup>−1</sup> and mol dm<sup>−3</sup> are the same unit.' },
    { el: null, q: 'In biochemistry, a concentration written as "0.10 M" means…',
      a: '0.10 mol dm<sup>−3</sup>', w: ['0.10 mol m<sup>−3</sup>', '0.10 mega-moles', '0.10 mg per mL'],
      x: 'M is shorthand for mol dm<sup>−3</sup> (mol L<sup>−1</sup>).' },
    { el: null, q: 'The prefixes m (milli) and M (mega) differ by a factor of…',
      a: '10<sup>9</sup>', w: ['10<sup>3</sup>', '10<sup>6</sup>', '1: they mean the same'],
      x: 'milli is 10<sup>−3</sup> and mega is 10<sup>6</sup>. Prefix symbols are case sensitive.' },
    { el: null, q: '1 µL is equal to…',
      a: '10<sup>−3</sup> mL', w: ['10<sup>−6</sup> mL', '10<sup>3</sup> mL', '10<sup>−3</sup> L'],
      x: '1 µL = 10<sup>−6</sup> L = 10<sup>−3</sup> mL (= 1 mm<sup>3</sup>). Micropipettes such as the P200 are labelled in µL.' },
    { el: null, q: 'Which prefix is 10<sup>−12</sup>, used for bond lengths?',
      a: 'pico (p)', w: ['nano (n)', 'micro (µ)', 'femto (f)'],
      x: 'Bond lengths are typically tens to hundreds of pm, for example 74 pm for H<sub>2</sub>.' },
    { el: null, q: 'A temperature change of 1 °C is the same as a change of…',
      a: '1 K', w: ['273.15 K', '274.15 K', '−272.15 K'],
      x: 'The degree Celsius and the kelvin are the same size; only the zero point differs (0 °C = 273.15 K). Absolute temperatures in equations must be in kelvin.' },
    { el: null, q: 'One ångström (Å) is…',
      a: '10<sup>−10</sup> m', w: ['10<sup>−9</sup> m', '10<sup>−12</sup> m', '10<sup>−6</sup> m'],
      x: '1 Å = 10<sup>−10</sup> m = 0.1 nm = 100 pm.' },
    { el: null, q: '1 cm<sup>3</sup> is how many m<sup>3</sup>?',
      a: '10<sup>−6</sup> m<sup>3</sup>', w: ['10<sup>−2</sup> m<sup>3</sup>', '10<sup>−3</sup> m<sup>3</sup>', '10<sup>6</sup> m<sup>3</sup>'],
      x: '1 cm = 10<sup>−2</sup> m, so 1 cm<sup>3</sup> = (10<sup>−2</sup> m)<sup>3</sup> = 10<sup>−6</sup> m<sup>3</sup>. The conversion factor is cubed too.' },
    { el: null, q: 'Gold has a density of 19.3 g cm<sup>−3</sup>. What is that in kg m<sup>−3</sup>?',
      a: '1.93 × 10<sup>4</sup> kg m<sup>−3</sup>', w: ['1.93 kg m<sup>−3</sup>', '1.93 × 10<sup>−2</sup> kg m<sup>−3</sup>', '1.93 × 10<sup>7</sup> kg m<sup>−3</sup>'],
      x: '× (1 kg / 1000 g) × (10<sup>6</sup> cm<sup>3</sup> / 1 m<sup>3</sup>). Using 10<sup>2</sup> instead of 10<sup>6</sup> gives 1.93 kg m<sup>−3</sup>: a cubic metre of gold weighing as much as a bag of sugar.' },
    { el: null, q: 'The molar absorption coefficient ε has units mol<sup>−1</sup> dm<sup>3</sup> cm<sup>−1</sup>. Why is dm<sup>3</sup> on the top line?',
      a: 'Dividing by a concentration (mol dm<sup>−3</sup>) puts dm<sup>3</sup> on top', w: ['Because ε is a volume', 'It is a typing convention with no meaning', 'Because the cuvette is 1 dm long'],
      x: 'Units come from the calculation that produces the quantity. Dividing by mol dm<sup>−3</sup> gives mol<sup>−1</sup> dm<sup>3</sup>.' },
    { el: null, q: 'Enzyme specific activity has units of µmol min<sup>−1</sup> mg<sup>−1</sup>. Which formula fits? (n = product formed, t = time, m = enzyme mass)',
      a: 'n / (t × m)', w: ['n × t / m', 'm / (n × t)', 'n × m / t'],
      x: 'µmol is on top, so an amount goes on top. min<sup>−1</sup> and mg<sup>−1</sup> are negative powers, so time and mass both go underneath.' },
    { el: null, q: 'Using n = m/M with m in g and M in g mol<sup>−1</sup>, what are the units of n?',
      a: 'mol', w: ['g<sup>2</sup> mol<sup>−1</sup>', 'mol<sup>−1</sup>', 'g mol'],
      x: 'g ÷ g mol<sup>−1</sup> = mol. If the units of your answer are not what you wanted, you have rearranged something incorrectly.' },
    { el: null, q: 'In E = hν, h is in J s and ν in s<sup>−1</sup>. What are the units of E?',
      a: 'J', w: ['J s<sup>2</sup>', 'J s<sup>−1</sup>', 's<sup>−1</sup>'],
      x: 'J s × s<sup>−1</sup> = J. Units are a free check on your algebra.' },
    { el: null, q: 'To find ν from c = λν, you should calculate…',
      a: 'ν = c / λ', w: ['ν = cλ', 'ν = λ / c', 'ν = c − λ'],
      x: 'Divide both sides by λ. Check with units: m s<sup>−1</sup> ÷ m = s<sup>−1</sup>.' },

    // Significant figures and precision
    { el: null, q: 'How many significant figures does "1500 g" have?',
      a: 'You can\'t tell: it could be 2, 3 or 4', w: ['2', '4', '0'],
      x: 'Trailing zeros in a whole number are ambiguous. Standard form removes the doubt: 1.5 × 10<sup>3</sup>, 1.50 × 10<sup>3</sup> or 1.500 × 10<sup>3</sup> g.' },
    { el: null, q: '0.0230 has how many significant figures and how many decimal places?',
      a: '3 s.f. and 4 d.p.', w: ['4 s.f. and 4 d.p.', '3 s.f. and 3 d.p.', '5 s.f. and 4 d.p.'],
      x: 'Leading zeros never count as significant figures, but the trailing zero after the decimal point does.' },
    { el: null, q: 'n = cV = 0.10 mol dm<sup>−3</sup> × 0.02357 dm<sup>3</sup>. The calculator shows 0.002357. How should n be reported?',
      a: '2.4 × 10<sup>−3</sup> mol', w: ['2.357 × 10<sup>−3</sup> mol', '2 × 10<sup>−3</sup> mol', '0.002357 mol'],
      x: 'When multiplying, keep the fewest significant figures of the inputs: 0.10 has 2 s.f.' },
    { el: null, q: 'Reporting a result as 2.4 × 10<sup>−3</sup> mol tells the reader the true value is probably between…',
      a: '2.35 and 2.45 × 10<sup>−3</sup> mol', w: ['2.3565 and 2.3575 × 10<sup>−3</sup> mol', '1.5 and 2.5 × 10<sup>−3</sup> mol', '2.0 and 3.0 × 10<sup>−3</sup> mol'],
      x: 'The number of figures you quote communicates how much tolerance to put around the value.' },
    { el: null, q: 'A dinosaur skeleton was "70 million years old" twelve years ago. Why is "70 million and twelve years" wrong?',
      a: 'Adding a precise number cannot make an imprecise one more precise', w: ['Twelve years is too short to measure', 'Ages must be in standard form', 'You can only add numbers with the same units'],
      x: 'The uncertainty is millions of years. When adding or subtracting, keep the fewest decimal places (here, the least precise place value).' },
    { el: null, q: 'Subtracting 25.5 cm<sup>3</sup> from 29.2 cm<sup>3</sup> gives 3.7 cm<sup>3</sup>. What has happened to the precision?',
      a: 'Still 1 d.p., but only 2 s.f.: subtracting similar numbers loses significant figures', w: ['It gains a significant figure', 'Nothing: it is still 3 s.f.', 'It becomes exact'],
      x: 'A ±0.1 cm<sup>3</sup> reading error is small next to 29.2 but large next to 3.7. That is why a bigger sample gives a better density.' },
    { el: null, q: 'In a formula like 2AgNO<sub>3</sub> + MgCl<sub>2</sub> → …, does the "2" limit the significant figures of your answer?',
      a: 'No: stoichiometric numbers are exact', w: ['Yes: it has 1 s.f.', 'Yes: it has 2 s.f.', 'Only when multiplying'],
      x: 'Exact numbers (counts, stoichiometries, defined constants) have unlimited significant figures.' },
    { el: null, q: 'To get a more precise final answer, which measurement should you improve first?',
      a: 'The least precise one', w: ['The most precise one', 'The largest one', 'The one measured last'],
      x: 'Your answer is only as good as your worst measurement.' },

    // Multi-step calculations
    { el: null, q: 'To find the energy of one mole of 280 nm photons, what is the first step?',
      a: 'Convert 280 nm to metres', w: ['Multiply by N<sub>A</sub>', 'Calculate E = hν', 'Divide by h'],
      x: 'Plan backwards (J mol<sup>−1</sup> ← E × N<sub>A</sub> ← E = hν ← ν = c/λ ← λ in m), then work forwards starting with the unit conversion.' },
    { el: null, q: 'Rounding each step of the 280 nm calculation to 2 s.f. gives 4.4 × 10<sup>5</sup> J mol<sup>−1</sup> instead of 4.28 × 10<sup>5</sup>. What is the lesson?',
      a: 'Keep values in the calculator and round only at the end', w: ['Always use 2 s.f.', 'Round to 1 s.f. instead', 'The constants are wrong'],
      x: 'Rounding errors build up along a chain. Carry results forward with Ans or the memory; write values down, but do not retype them.' },
    { el: null, q: 'What is the energy of one mole of 280 nm photons? (the chain from the lecture)',
      a: '428 kJ mol<sup>−1</sup>', w: ['7.10 × 10<sup>−19</sup> kJ mol<sup>−1</sup>', '0.428 kJ mol<sup>−1</sup>', '4.28 × 10<sup>8</sup> kJ mol<sup>−1</sup>'],
      x: 'ν = 1.071 × 10<sup>15</sup> s<sup>−1</sup>; E = 7.10 × 10<sup>−19</sup> J per photon; × 6.022 × 10<sup>23</sup> = 4.28 × 10<sup>5</sup> J mol<sup>−1</sup> = 428 kJ mol<sup>−1</sup>.' },

    // Amount of substance
    { el: null, q: 'For n = cV with c in mol dm<sup>−3</sup>, V must be in…',
      a: 'dm<sup>3</sup>', w: ['mL', 'cm<sup>3</sup>', 'm<sup>3</sup>'],
      x: 'The volume unit must match the concentration unit. 9.85 mL = 9.85 × 10<sup>−3</sup> dm<sup>3</sup>.' },
    { el: null, q: 'A student works out moles in 9.85 mL of 0.0100 M AgNO<sub>3</sub> as 0.01 × 9.85 = 0.0985 mol. What went wrong?',
      a: 'The volume wasn\'t converted to dm<sup>3</sup>: the answer is 1000 times too big', w: ['Nothing: 0.0985 mol is right', 'M should have been converted to mol m<sup>−3</sup>', 'They should have divided instead of multiplied'],
      x: 'n = 0.0100 mol dm<sup>−3</sup> × 9.85 × 10<sup>−3</sup> dm<sup>3</sup> = 9.85 × 10<sup>−5</sup> mol.' },
    { el: null, q: '2AgNO<sub>3</sub> + MgCl<sub>2</sub>·6H<sub>2</sub>O → 2AgCl + … If 9.85 × 10<sup>−5</sup> mol AgNO<sub>3</sub> reacted, how much MgCl<sub>2</sub>·6H<sub>2</sub>O was present?',
      a: '4.93 × 10<sup>−5</sup> mol', w: ['1.97 × 10<sup>−4</sup> mol', '9.85 × 10<sup>−5</sup> mol', '5.91 × 10<sup>−4</sup> mol'],
      x: '2 mol AgNO<sub>3</sub> react with 1 mol MgCl<sub>2</sub>·6H<sub>2</sub>O, so divide by 2.' },
    { el: null, q: 'Why must the "·6H<sub>2</sub>O" be included in the molar mass of MgCl<sub>2</sub>·6H<sub>2</sub>O?',
      a: 'Six water molecules are part of every formula unit', w: ['It is only there to show the salt is wet', 'Water has no mass on the atomic scale', 'It only matters for concentrations'],
      x: 'MgCl<sub>2</sub>·6H<sub>2</sub>O is 203.31 g mol<sup>−1</sup>; MgCl<sub>2</sub> alone is 95.21. Leaving the water out sends an identification to the wrong answer.' },
    { el: null, q: 'In the chloride titration, Ag<sup>+</sup> + Cl<sup>−</sup> → AgCl. For a group 2 chloride XCl<sub>2</sub>, moles of salt are…',
      a: 'half the moles of Ag<sup>+</sup> used', w: ['equal to the moles of Ag<sup>+</sup> used', 'twice the moles of Ag<sup>+</sup> used', 'impossible to find'],
      x: 'Each Ag<sup>+</sup> removes one Cl<sup>−</sup>, and each XCl<sub>2</sub> supplies two Cl<sup>−</sup>.' },
    { el: null, q: 'The titration gives M = 0.10 ÷ 4.93 × 10<sup>−4</sup> = 202.8… g mol<sup>−1</sup>. With 0.10 g and 0.10 mol dm<sup>−3</sup>, how should it be reported?',
      a: '2.0 × 10<sup>2</sup> g mol<sup>−1</sup>', w: ['202.8 g mol<sup>−1</sup>', '203 g mol<sup>−1</sup>', '200.0 g mol<sup>−1</sup>'],
      x: 'The mass and concentration are both known to only 2 s.f., so the answer is 2 s.f. Standard form shows that clearly.' },
  ]
});
